### PR TITLE
Replaces usages of Generator.DottedName with Generator.TypeExpression

### LINKED ISSUE #748: CodeFixers should prefer using Generator.TypeExpression over Generator.DottedName
The former ensures that the code generation and simplification engine produces the best code that will bind to the symbol passed in.  The latter does not.  For example, the former may decide that "global::" qualification is necessary to prevent the code from binding to a symbol that shadows the actual symbol the fixer wants to reference.

### PR DESCRIPTION
**Pull request by bkoelman**
Fixes #748.

### CODE REVIEW

**Comment by bkoelman** [comment]
Tagging @CyrusNajmabadi for review

**Comment by srivatsn** [comment]
👍

**Comment by CyrusNajmabadi** [comment]
LGTM.  Are there other places in the analyzers we can do this as well?

**Comment by bkoelman** [comment]
I did not find any. Maybe in other repositories...

**Pull request merged**
