### PR TITLE
Find msbuild under 'MSBuild\Current\Bin' for Dev16

### PR DESCRIPTION
**Pull request by mavasani**

### CODE REVIEW

**Comment by tmat** [comment]
We should just copy `build.ps1` and `tools.ps1` from the `eng\common` directory in Roslyn.

**Comment by mavasani** [comment]
@tmat Any guidance on this one?

**Comment by mavasani** [comment]
@sharwell Let me talk to Tomas and see if he has a suggestion to unblock this PR trivially, otherwise, I will create a separate PR with just the original commit and merge it in today.

**Comment by mavasani** [comment]
Talked with @tmat - he will clean this up later. I am going to create a separate PR with the quick fix and leave this one open for his reference.

**Comment by mavasani** [comment]
@sharwell I have merged https://github.com/dotnet/roslyn-analyzers/pull/2081 to unblock.

**Comment by mavasani** [comment]
closing stale PR

**Pull request closed without merging**
