### PR TITLE
Refactor public API analyzer and symbol banned API analyzer into ApiS…

### PR DESCRIPTION
**Pull request by mavasani**
…urface.Analyzers

Verified with CI build that we generate a new ApiSurface.Analyzers NuGet package with these two analyzer related rules only. I have also added a NuGet package dependency from Roslyn.Diagnostics.Analyzers to ApiSurface.Analyzers so that existing package consumers are not broken and would not need any updates.

### CODE REVIEW

**Comment by mavasani** [comment]
Also tagging @AArnott

**Comment by mavasani** [comment]
Open to naming suggestions for the new analyzer package.

**Comment by AArnott** [comment]
Ya, ApiSurface.Analyzers makes it sound like it will help me develop a good API that follows framework guidelines, but I guess there are other analyzer packages that already exist and do that. 

The two analyzers in this package don't have much in common -- one helps a library author maintain the public API (i.e. completely useless to the library's consumer), and the other analyzer targets consumption of APIs. Should these two even be in the same analyzer package? It seems hard to name a thing when the only two analyzers serve different audiences.

**Comment by dotpaul** [comment]
Whatever the package name is, how about starting with "Microsoft." so that it has a reserved prefix in nuget.org?  See https://docs.microsoft.com/en-us/nuget/reference/id-prefix-reservation

**Comment by mavasani** [comment]
> The two analyzers in this package don't have much in common -- one helps a library author maintain the public API (i.e. completely useless to the library's consumer), and the other analyzer targets consumption of APIs

I felt that these are complimentary to each other for configuring the incoming and outgoing API surface for a project/library:
1. which external APIs am I allowed (or disallowed) to invoke/use in this project and
2. which APIs of this project am I allowed to break (or not break) as these are invoked by project's external consumers

Also note that both these analyzers are based off additional API configuration files, and hence the rules are essentially disabled by default. Additionally, they have a very similar API surface configuration files, with almost identical formats.

> Whatever the package name is, how about starting with "Microsoft." so that it has a reserved prefix in nuget.org?

I am in two minds here. The rest of our analyzer packages (except Text.Analyzers and Roslyn.Diagnostics.Analyzers) are prefixed with Microsoft as they contain generic Microsoft recommended code quality rules or rules about correct usage of some of our APIs (such as IDisposable, security APIs, etc.). These rules have CAxxxx IDs, for which we have documentation on docs.microsoft.com and are also supported by Microsoft. The two analyzers in this package have nothing that is Microsoft recommended, but are generic API configuration analyzers, they can probably even be pulled into a separate repo. On the other hand, given these are coming out from Microsoft supported repo, and majority of our analyzer packages in this repo are prefixed with Microsoft, the prefix would make it symmetrical and easy to search/group on NuGet.

**Comment by AArnott** [comment]
> I felt that these are complimentary to each other for configuring the incoming and outgoing API surface for a project/library:

Interest in banning external APIs doesn't strike me as unique to library authors. If you're writing an app you might need to ban consumption of certain APIs as well. I'm not sure how often one library should appropriately ban its consumer's use of *another* library's APIs. Why would my consumption of **A** ban me from using parts of **B**? From the VS SDK standpoint, we want to ban other libraries' APIs because we're an *app*, and folks who write code for running within our app need to abide by our rules for stability and performance.

Given that (and I'm happy to be told otherwise if I'm ignorant of a scenario), I tend to bucket these two analyzers separately:

1. PublicAPI.txt: As a library author, helps me monitor my public API changes. I would *never* want to downstream this to my consumers.
1. Banned APIs: As an app owner, helps me block my downstream SDK consumers from doing bad things in my app.

Put another way:

| Analyzer | Project type | Downstream interest? 
| -- | -- | -- |
| PublicAPIs.txt | Library | No
| Banned APIs | App | Yes

Given the downstream interest is exactly opposing each other, I might find it difficult to decide whether to use this package since I have to decide whether to make the package dependency public as an app author so downstream consumers get it (possibly getting N/A analyzers) or to keep it hidden as a library author and deal with a Banned APIs analyzer that has no applicability.

The saving grace right now is that both analyzers (presumably) are very cheap to run when their AdditionalFiles are missing, so if they are n/a, they probably don't actually hurt anything. But will that be true for *every* analyzer added to this package? If not, it might be best to split the package into the two bucketed scenarios now so that folks can choose which slice to consume and which one to make available downstream.

**Comment by mavasani** [comment]
@AArnott In that case it probably seems fine to separate out just the banned API analyzer into the new package, such that in future it can be moved out into a separate repo, just like https://github.com/DotNetAnalyzers/PublicApiAnalyzer. Any suggestions for the name of this new analyzer package?

**Comment by AArnott** [comment]
How about `DotNetAnalyzers.BannedApiAnalyzer`?

That would fit with the public api analyzer naming pattern set in the one you linked to.

**Comment by genlu** [comment]
@mavasani What's the relation between the public API analyzer in this repo and [https://github.com/DotNetAnalyzers/PublicApiAnalyzer](https://github.com/DotNetAnalyzers/PublicApiAnalyzer)? They look almost identical from a a quick glance.

**Comment by mavasani** [comment]
@genlu It was forked at a point of time by Sam so it can be published and consumed as a separate analyzer package. It also targets Microsoft.CodeAnalysis 1.x, so potentially can be used in projects built with prior versions of VS/compiler toolset. Functionality wise, I believe we have added many more bug fixes to the copy in this repo, as it is actively dogfooded and fixed in Roslyn.sln. Also we have lot more unit tests, including VB tests, which is missing in https://github.com/DotNetAnalyzers/PublicApiAnalyzer.

I believe the eventual goal is to separate out such generic analyzers into separate NuGet package(s) and/or repo(s), so we avoid similar situation in future where we have multiple copies of the implementations floating around. This PR was an attempt at the first step towards it, but based on an offline conversation it might seem that the best way forward might be to do the following:

1. Banned API analyzer refactoring:
   1. Separate out the Banned API analyzer into a separate repo, say https://github.com/DotNetAnalyzers/BannedApiAnalyzer
   2. Delete the Banned API analyzer sources from roslyn-analyzers repo + add NuGet package dependency from Roslyn.Diagnostics.Analyzers to BannedApiAnalyzer so existing clients of Roslyn.Diagnostics.Analyzers are not broken.

2. Public API analyzer refactoring:
   1. Sync all the bug fixes and unit tests from Public API analyzer in this repo into https://github.com/DotNetAnalyzers/PublicApiAnalyzer
   2. Delete the Public API analyzer ources from roslyn-analyzers repo + add NuGet package dependency from Roslyn.Diagnostics.Analyzers to PublicApiAnalyzer so existing clients of Roslyn.Diagnostics.Analyzers are not broken.

@sharwell @AArnott @Pilchie @drewnoakes @jinujoseph - if you agree with the above, I will abandon this PR and would need someone to sign up to do this work. I feel it would be appropriate for @Pilchie or @drewnoakes to take up Banned API analyzer refactoring and Sam or I can do the Public API analyzer refactoring.

**Comment by genlu** [comment]
@mavasani Thanks for the explaination. This proposal sounds good to me. If everybody agrees on it, maybe I can help on separating BannedAPI analyzer (assume @sharwell can create a repo over at DotNetAnalyzers)

**Comment by sharwell** [comment]
> Functionality wise, I believe we have added many more bug fixes to the copy in this repo, as it is actively dogfooded and fixed in Roslyn.sln

It's generally stayed up-to-date as changes were made here. I think the only thing missing is the recent change to VB auto-properties.

**Comment by mavasani** [comment]
Closing this PR for now, @genlu will drive the Banned API analyzer refactoring.

**Pull request closed without merging**
