### PR TITLE
Create packages on build

### PR DESCRIPTION
**Pull request by sharwell**
This pull request fixes a bug where none of the analyzer NuGet packages were getting created during the build process.

### CODE REVIEW

**Comment by tmat** [comment]
I don't understand what the problem is. The packages get created during Pack build phase (`msbuild /t:pack`). This is intentional.

**Comment by sharwell** [comment]
@tmat Why? In the IDE, I expect to be able to right click one of the Package projects and select build, and have it produce the package. Currently that does not happen, and I couldn't find any clear reason why they would be blocked.

**Comment by tmat** [comment]
Building packages slows down the build. 

You can click on a project and select "Pack" to create a nuget package:

image

Is there a scenario in which you need to build a package on every F5?

**Comment by sharwell** [comment]
> Building packages slows down the build.

I'm having trouble getting the exact amount of time we're talking about because the up-to-date check is currently broken for this solution (causing a bunch of projects to get build unnecessarily).

> Is there a scenario in which you need to build a package on every F5?

This change does not impact the F5 experience.

**Comment by tmat** [comment]
> This change does not impact the F5 experience. 

How come? If anything is changed in the source a build is triggered. If packages are produced on build then they will be produced on F5 as well. I just don't see any scenario where you'd need to package on every build.

**Comment by tmat** [comment]
> the up-to-date check is currently broken for this solution

That would be good to get fixed.

**Comment by sharwell** [comment]
> How come? If anything is changed in the source a build is triggered. If packages are produced on build then they will be produced on F5 as well.

F5 builds the startup project. Since nothing references the \*.Package projects, no startup project will cause these to build on F5.

> Building packages slows down the build.

For my experiment, I fixed the up-to-date check for unit test projects so that bug wouldn't impact my results.

A change to VersionCheckAnalyzer results in a 26 second incremental build (Build &rarr; Build Solution) with this change. Without this change, the same build took 31 seconds. I tried to use a consistent approach to testing, but wasn't _extremely_ rigorous since I was trying to determine the magnitude of the difference as a consideration for how to proceed. My conclusion from this experiment is the build impact from packaging is at worst negligible.

**Comment by sharwell** [comment]
> That would be good to get fixed.

I added the fix to #1608

**Comment by tmat** [comment]
> F5 builds the startup project. Since nothing references the *.Package projects, no startup project will cause these to build on F5.

I see. This is because we have separate projects for building NuGet packages, instead of having the source projects themselves to produce packages. So yes, in this particular scenario F5 won't be affected as it would be if projects produce their own packages.

I'd still like to hear why do you expect the packages to be produced by build. It's not the default behavior of .NET SDK based projects.

Also consider that changing the analyzer package projects to produce nuget packages on build will be inconsistent with how any other repo produces packages.

**Comment by tmat** [comment]
BTW, the build failure is likely caused by https://github.com/NuGet/Home/issues/6165.
See also https://github.com/dotnet/roslyn-tools/blob/pre-SDK/sdks/RepoToolset/tools/Build.proj#L188-L195

**Comment by sharwell** [comment]
> I'd still like to hear why do you expect the packages to be produced by build. It's not the default behavior of .NET SDK based projects.

This is a submission of a very old side branch in my local copy. The original cause could have been any of the following:

1. I couldn't figure out how to create packages
2. It didn't make sense to have a project whose only purpose is to create packages do nothing when built
3. It broke the up-to-date check for the packages projects

In some way or another I remember it interfering with my ability to run AnalyzerRunner tests against the FXCop analyzers.

> Also consider that changing the analyzer package projects to produce nuget packages on build will be inconsistent with how any other repo produces packages.

The separate pack command will still work the same way it did before.

**Comment by tmat** [comment]
> I couldn't figure out how to create packages

I'm not sure why isn't it obvious how to build a nuget package. `dotnet pack` is a well known command that corresponds to `msbuild /t:pack` when building with desktop msbuild.

Would documenting it in https://github.com/dotnet/roslyn-analyzers/readme.md help?

> It didn't make sense to have a project whose only purpose is to create packages do nothing when built

Why? We do have projects whose only purpose is to do packaging. Some of them build NuGet packages [others](https://github.com/dotnet/project-system/blob/master/setup/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles/Microsoft.VisualStudio.ProjectSystem.Managed.CommonFiles.csproj) build Willow VSIX, or other containers. These artifacts are not useful in inner-loop scenarios. They are only useful when publishing/inserting into VS, etc. There is no point spending time on building them outside of CI.

> It broke the up-to-date check for the packages projects

I'd like to understand why is the up-to-date check broken by having no-op build target. Can we fix it?

> Projects that map 1:1 to a NuGet package should create that package on build, but it's not a default.

I disagree. Ideally, artifacts that are not needed for inner-loop development should not be produced by the Build target.

**Comment by sharwell** [comment]
> Ideally, artifacts that are not needed for inner-loop development should not be produced by the Build target.

:memo: I tend to agree strongly with this when/where it imposes a performance problem. However, for all of the severe issues I've observed with analyzer development inner loop performance, creating the package has not resulted in observable overhead.

**Comment by tmat** [comment]
@sharwell You are looking at a single repository though. Would it not be a problem if we did this in Roslyn as well? I'd rather keep things consistent. Otherwise people working with multiple repositories will be confused about which build actions produce packages and which don't.

**Comment by 333fred** [comment]
Agreed with @tmat here. I very rarely need to use the nuget packages in this repo, and I frequently hit build all because I want to compile both test and vsix. I don't want that slowing down. Additionally, as mentioned, this would become inconsistent with every other roslyn repo.

**Comment by sharwell** [comment]
>  I don't want that slowing down. 

This pull request appears to make the incremental build faster, not slower.

**Comment by mavasani** [comment]
> It didn't make sense to have a project whose only purpose is to create packages do nothing when built

Would it make sense to not have these projects in the RoslynAnalyzers.sln at all? We can either conditionally include them in the solution for CI build OR have the build targets appropriately build these projects separately during CI builds.

@sharwell - I understand the requirement from AnalyzerRunner to work on NuGet pacakges, but that is a very special operation, for which one can either use CIBuild script or add configuration/switches to the core build script to enable opting into building packages on build. I agree with @tmat and @333fred that we should not produce artifacts in a default local build that are hardly ever used by devs and unnecessarily bloat up disk space.

**Comment by tmat** [comment]
> Would it make sense to not have these projects in the RoslynAnalyzers.sln at all? We can either conditionally include them in the solution for CI build OR have the build targets appropriately build these projects separately during CI builds.

I'm not sure what problem are we trying to solve here. If an incremental build is broken today for the packaging projects that produce no binaries then let's fix that. 

What else would excluding packaging projects from the solution achieve, other than more complexity and inconsistency that occurs since `msbuild /t:pack RoslynAnalyzers.sln` would not produce packages (or would only produce some packages if we had a project that produces both a binary and a package)?

**Comment by sharwell** [comment]
I would request that this be enabled after the build machines are updated on the following basis:

1. It doesn't make the build slower, and even if the FUTDC is fixed for the package projects it won't make the build slower for inner loop development
2. It does not alter the behavior of any existing workflows other people may be using
3. I found it less confusing

In other words, I believe I have addressed the expressed concerns over downsides to an extent that would allow the decision to be made on the basis of personal preference for an additional workflow.

**Comment by tmat** [comment]
The main concern has not been addressed:
> I'd rather keep things consistent. Otherwise people working with multiple repositories will be confused about which build actions produce packages and which don't.
> Also I'd like to stick closer to the default behavior of dotnet CLI. We have dotnet build and dotnet pack as two distinct operations and it's very clear what they do by default.

In other words, I'd find it more confusing to produce some packages during build and other packages during pack.

**Comment by mavasani** [comment]
@sharwell Can we close this pull request?

**Comment by sharwell** [comment]
@mavasani Sure, if I hit the case that led me to create it the first time I'll reopen it

**Pull request closed without merging**
