### PR TITLE
Remove explicit dependency on roslyn used to build

### PR DESCRIPTION
**Pull request by mmitche**
This will remove the override of the version of roslyn used to build this repo

### CODE REVIEW

**Comment by Evangelink** [comment]
Does it mean that after this change the version of roslyn used is the one on the machine?

**Comment by mmitche** [comment]
> Does it mean that after this change the version of roslyn used is the one on the machine?

Nope, it means that it comes from arcade, and is not overridden.

**Comment by mmitche** [comment]
@jmarolf or @mavasani Can you take a look at the errors and push to this branch?

**Comment by mavasani** [comment]
Interesting, I cannot repro this locally on a 16.9 P2 build, digging further..

**Review by jmarolf — APPROVED** [review]

**Comment by mavasani** [comment]
I have added a pragma suppression with https://github.com/dotnet/roslyn-analyzers/pull/4347/commits/2e6b79b402e2b7ee21831fb3693ee5b3b7ebe471 and filed https://github.com/dotnet/roslyn-analyzers/issues/4350 to track reverting the suppression and fixing it appropriately.

**Review by mavasani — APPROVED** [review]

**Pull request merged**
