### PR TITLE
Update AnalyzerPowerPack version number

### PR DESCRIPTION
**Pull request by tmeschter**
Update the AnalyzerPowerPack version number from 1.0.1 to 1.0.2. We
have already shipped 1.0.1.

### CODE REVIEW

**Comment by tmeschter** [comment]
@srivatsn @genlu @mavasani Please review.

**Comment by srivatsn** [comment]
This is true for all the other analyzers as well isn't it? Shouldn't we update the System.*.Analyzers and Microsoft.CodeAnalysis.Analzyers versions as well?

**Comment by tmeschter** [comment]
@srivatsn We've only released version 1.0.0 of Microsoft.CodeAnalysis.Analyzers, so the next version will be at least 1.0.1; the file already reflects that.

**Comment by genlu** [comment]
:+1:

**Pull request merged**
