### PR TITLE
Use Visual Studio 2019 for builds

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by mavasani** [comment]
Seems builds are failing even without executing.

**Comment by mavasani** [comment]
Tagging @JoeRobich in case he has ideas on how to resolve this.

**Comment by JoeRobich** [comment]
@sharwell Just curious, Is there a catalog of queues that we can specify?

**Comment by sharwell** [comment]
@JoeRobich I found it here: https://github.com/dotnet/arcade-pool-provider/blob/master/src/appsettings.dncengpublic-prod.json

**Pull request merged**
