### PR TITLE
Fix typo in RS0030 message: "Do not used banned APIs" -> "Do not use banned APIs"

### PR DESCRIPTION
**Pull request by sorensenmatias**
Fix typo in RS0030 message: "Do not used banned APIs" -> "Do not use banned APIs"

### CODE REVIEW

**Review by Evangelink — COMMENTED** [review]
Overall LGTM but I expect some build issue on localization files as the content is still appearing as "translated". Did you run `msbuild /t:pack /v:m` as recommended when opening the PR?

Thanks for the contribution @sorensenmatias

**Comment by Evangelink** [comment]
@mavasani Is PR ok as-is or are we supposed to have the localization files translation status reset?

**Comment by Youssef1313** [comment]
Running pack didn't produce any changes because `xlf` files were manually modified. So, the UpdateXlf task can't really know that the state needs to be updated.

Merging the PR as-is might cause issues. The changes in `xlf` should be reverted, then `dotnet msbuild /t:pack /v:m` should be run.

**Comment by sorensenmatias** [comment]
Thanks.
I reverted the changes to `xlf` files and pushed the commit, but running `dotnet msbuild /t:pack /v:m` still does not produce anything. What else is missing?

**Comment by sorensenmatias** [comment]
@Youssef1313 Thanks, but running that instead still does not produce anything.

**Comment by Youssef1313** [comment]
Do you see any errors? 
What is the output of the command?

**Comment by Youssef1313** [comment]
@sorensenmatias You can merge https://github.com/sorensenmatias/roslyn-analyzers/pull/1 if you couldn't do it yourself locally, but it's definitely good to understand the problem you're having.

**Comment by sorensenmatias** [comment]
@Youssef1313 Thanks a lot - it is merged.

**Review by Youssef1313 — APPROVED** [review]

**Comment by Youssef1313** [comment]
@mavasani Can you take a look and merge please?

**Review by mavasani — APPROVED** [review]

**Pull request merged**
