### PR TITLE
Fixed compiler errors in Microsoft.Maintainability.Analyzers.UnitTests

### PR DESCRIPTION
**Pull request by bkoelman**
Overview of typical issues in unittest code fragments:
* Copy/paste errors
* Missing imports
* Scoping errors (use private type in public signature)
* Poor translations from C# to VB
* `out` variables not assigned

### CODE REVIEW

**Comment by bkoelman** [comment]
retest please

**Comment by mavasani** [comment]
retest please

**Comment by mavasani** [comment]
@dotnet-bot retest this please

**Comment by mavasani** [comment]
:+1:

**Pull request merged**
