### PR TITLE
Bail out from conversion inference for user-defined conversions

### LINKED ISSUE #6435: Wrong CA1508 when struct has a userd-defined conversion to nullable reference type
### Analyzer

**Diagnostic ID**: [CA1508](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.NetAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.NetAnalyzers)

**Version**: 7.0.102

### Describe the bug

When a `struct` has a user-defined conversion (either `explicit operator` or `implicit operator`) to a _nullable_ reference type, the CA1508 emits false positives. This was noted when using `StackExchange.Redis.RedisValue` which has such an operator, but for simplicity is reproduced with struct `S` below.

### Steps To Reproduce

Make a C# program like this:
```csharp
#nullable enable

public readonly struct S {
    public int I { get; init; }

    public static explicit operator byte[]?(S s) {
        if (s.I < 0) {
            return null;
        }
        return new byte[s.I];
    }
}

public static class C {

    public static bool M(S s) {
        byte[]? a = (byte[]?)s;
        bool b = a == null;      // incorrect CA1508; this b could be true or false
        return b;
    }

    private static void Main() {
        bool r = M(new S { I = -1, });
    }
}
```
In method `M`, the Boolean `b` could clearly be true, but CA1508 claims it is always false.

Also happens with `implicit operator` (like in `RedisValue` struct).

### Expected behavior
No code analysis error.

### Actual behavior
False positive `Error CA1508 'a == null' is always 'false'. Remove or refactor the condition(s) to avoid dead code.` emitted from the line where `b` is declared.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #6435

### CODE REVIEW

**Comment by mavasani** [comment]
@Youssef1313

**Comment by mavasani** [comment]
> Would this introduce false negatives for properly written conversions?
> 
> For example, `System.Xml.Linq` defines some conversions from `XElement` to various other types (string for example).
> 
> So, if in place of `S` we have `XElement`, and in place of `byte[]?` we have `string?`, we will not warn, but we should?

Yes, but unless we hardcode operator methods on such well-known types OR analyze the operator method body, we can not avoid those. We do bail out at bunch of places in flow analysis for user defined conversions, so this change is in line with the conservativeness: https://github.com/dotnet/roslyn-analyzers/blob/47edf21cd38fb583da54085bdfd724c2cdf1f6f0/src/Utilities/FlowAnalysis/FlowAnalysis/Framework/DataFlow/DataFlowOperationVisitor.cs#L3069-L3075

**Review by Youssef1313 — APPROVED** [review]

**Comment by mavasani** [comment]
Thanks @Youssef1313

**Comment by JeppeSN** [comment]
> > Would this introduce false negatives for properly written conversions?
> > For example, `System.Xml.Linq` defines some conversions from `XElement` to various other types (string for example).
> > So, if in place of `S` we have `XElement`, and in place of `byte[]?` we have `string?`, we will not warn, but we should?
> 
> Yes, but unless we hardcode operator methods on such well-known types OR analyze the operator method body, we can not avoid those. We do bail out at bunch of places [...] 

In general, it is impossible to analyze deeply the body of the user-defined operator (like solving the halting problem, I suppose). But for the specific case of `public static explicit operator string?(XElement? element)`, the authors of the operator have been careful to add an attribute `[return: NotNullIfNotNull(nameof(element))]`. This clearly makes a promise that if the `element` is a reference to an actual instance (i.e. not null), then so is the returned `string?` reference. This attribute could of course be taken advantage of.
```
    static void M(XElement e) {
        var s = (string?)e;
        var i = s == null ? 1 : 2;
    }
```

**Pull request merged**
