### PR TITLE
Handle reference to non-source symbols in UseConcreteTypeAnalyzer

### LINKED ISSUE #6852: IndexOutOfRangeException in UseConcreteTypeAnalyzer (CA1859)
### Analyzer

**Diagnostic ID**: [CA1859](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA1859): `Use concrete types when possible for improved performance`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 8 SDK or later](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: `SDK 8.0.0-preview.23364.2`

### AD0001 analyzer exception diagnostic

Exception seen while working on Roslyn.sln

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Performance.UseConcreteTypeAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'.
Exception occurred with following context:
Compilation: Microsoft.CodeAnalysis.Workspaces
IOperation: Invocation
SyntaxTree: C:\roslyn\src\Workspaces\Core\Portable\Storage\SQLite\v2\SQLitePersistentStorage_Threading.cs
SyntaxNode: vt.Item1() [InvocationExpressionSyntax]@[3489..3499) (59,16)-(59,26)

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Analyzer.Utilities.AnalyzerOptionsExtensions.TryGetSyntaxTreeForOption(ISymbol symbol, SyntaxTree& tree)
   at Microsoft.NetCore.Analyzers.Performance.UseConcreteTypeAnalyzer.<>c__DisplayClass9_1.<Initialize>b__4(ISymbol symbol)
   at Microsoft.NetCore.Analyzers.Performance.UseConcreteTypeAnalyzer.Collector.HandleInvocation(IInvocationOperation op)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info, CancellationToken cancellationToken)
-----

Suppress the following diagnostics to disable this analyzer: CA1859	Microsoft.CodeAnalysis.Workspaces (netstandard2.0)	C:\roslyn\src\Workspaces\Core\Portable\Microsoft.CodeAnalysis.Workspaces.csproj	1	Active

```

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #6852

### CODE REVIEW

**Comment by mavasani** [comment]
@carlossanlop @jeffhandley - we may consider this for backporting to 8.0 as this fixes an analyzer exception case.

**Review by geeknoid — APPROVED** [review]

**Review by buyaa-n — APPROVED** [review]
LGTM, thank you!

**Comment by jeffhandley** [comment]
Looks good to me too. I will advocate for the backport to be approved once the issue template is filled out on #6960.

**Comment by buyaa-n** [comment]
> Looks good to me too. I will advocate for the backport to be approved once the issue template is filled out on #6960.

The template is filled

**Comment by jeffhandley** [comment]
As @artl93 [asked on the backport PR](https://github.com/dotnet/roslyn-analyzers/pull/6960#pullrequestreview-1638876792):

> is there a general pattern in this scenario here we should be considering validating more broadly?

@mavasani / @buyaa-n -- since this fix is isolated to this specific analyzer, should we scout out this category of bug across other analyzers? I don't know how often we have logic similar to this.

**Comment by buyaa-n** [comment]
Just did a quick check, the API `MatchesConfiguredVisibility` is used in many analyzers, mostly used for analyzing symbol actions and a few operation block analysis where the symbol is guaranteed to be in source (it is the analyzing symbol or the method of the analyzing operation block), I believe they are safe

Found only one similar case that might cause this issue (CA2234):
https://github.com/dotnet/roslyn-analyzers/blob/4aefee9f788e07c480a69518f38901bf7b19d9be/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/PassSystemUriObjectsInsteadOfStrings.cs#L91-L95

This is called for an invocation operation that could be referencing a method defined outside of the source:
https://github.com/dotnet/roslyn-analyzers/blob/4aefee9f788e07c480a69518f38901bf7b19d9be/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/PassSystemUriObjectsInsteadOfStrings.cs#L54

It might not noticed before because [this analyzer](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2234) is disabled by default

**Pull request merged**
