### PR TITLE
[release/6.0.1xx] Migrate to 1ES hosted pools

### PR DESCRIPTION
**Pull request by lpatalas**
We need to migrate pools to 1ES hosted pools. Only the yamls have to be changed. The supported functionality stays the same.

Tracking issue: https://github.com/dotnet/core-eng/issues/14276
/CC: @jonfortescue

### CODE REVIEW

**Comment by lpatalas** [comment]
Some tests failed but the logs does not contain the actual error. I can't see "Test execution summary" in the logs so it looks as if the runner crashed halfway. We had some problems in dotnet/roslyn related to the interactive login setting: https://github.com/dotnet/roslyn/pull/56186#issuecomment-917195917. I wonder if this may be related?

```
xUnit.net Console Runner v2.4.1 (64-bit Desktop .NET 4.7.2, runtime: 4.0.30319.42000)
  Discovering: Microsoft.CodeAnalysis.NetAnalyzers.UnitTests
  Discovered:  Microsoft.CodeAnalysis.NetAnalyzers.UnitTests
  Starting:    Microsoft.CodeAnalysis.NetAnalyzers.UnitTests
    Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.UnitTests.AvoidEmptyInterfacesTests.TestConflictingAnalyzerOptionsForPartialsAsync [SKIP]
      https://github.com/dotnet/roslyn-analyzers/issues/3494
    Microsoft.NetCore.Analyzers.Performance.UnitTests.PreferIsEmptyOverCountTests.CSharpTestIsEmptyGetter_NoDiagnosisAsync [SKIP]
      Removed default support for all types but this scenario can be useful for .editorconfig
    Microsoft.NetCore.Analyzers.Performance.UnitTests.PreferIsEmptyOverCountTests.BasicTestIsEmptyGetter_NoDiagnosisAsync [SKIP]
      Removed default support for all types but this scenario can be useful for .editorconfig
    Microsoft.NetCore.Analyzers.Performance.UnitTests.CSharpUsePropertyInsteadOfCountMethodWhenAvailableOverlapTests_Concurrent.NonZeroEqualsCount_WithoutPredicate_FixedAsync [SKIP]
      https://github.com/dotnet/roslyn-analyzers/issues/3700
    Microsoft.CodeQuality.Analyzers.Maintainability.UnitTests.DoNotIgnoreMethodResultsTests.UnusedComImportPreserveSigAsync [SKIP]
      https://github.com/dotnet/roslyn-analyzers/issues/746
=== COMMAND LINE ===
"D:\a\_work\1\s\.packages\xunit.runner.console\2.4.1\tools\net472\xunit.console.exe" "D:\a\_work\1\s\artifacts\bin\Microsoft.CodeAnalysis.NetAnalyzers.UnitTests\Debug\net472\Microsoft.CodeAnalysis.NetAnalyzers.UnitTests.dll" -noshadow -xml "D:\a\_work\1\s\artifacts\TestResults\Debug\Microsoft.CodeAnalysis.NetAnalyzers.UnitTests_net472_x64.xml" -html "D:\a\_work\1\s\artifacts\TestResults\Debug\Microsoft.CodeAnalysis.NetAnalyzers.UnitTests_net472_x64.html"  > "D:\a\_work\1\s\artifacts\log\Debug\Microsoft.CodeAnalysis.NetAnalyzers.UnitTests_net472_x64.log" 2>&1

```

**Comment by lpatalas** [comment]
I was trying to reproduce the error but I had no success. The tests pass successfully both on my local machine as well as on standalone VM created from the same image as we have on the 1ES pool. I'm a bit lost what could be the reason of the failure. We also see similar failures on main branch: https://github.com/dotnet/roslyn-analyzers/pull/5674.

@jmarolf Do you have any suspicion what could be the reason for the test failures in this PR? I would really appreciate some tips on how to solve it.

**Comment by jmarolf** [comment]
@lpatalas can you add this to the pipeline: https://github.com/dotnet/roslyn-sdk/blob/9e0d174c165bccdc18f8231c4268b1a19f2be420/.vsts-pr.yaml#L52-L55

so we can get dumps of what is happening?

**Comment by mavasani** [comment]
@lpatalas Is this PR still relevant?

**Comment by lpatalas** [comment]
I still see two places where old pools are used so I think it's still relevant. @jmarolf and @JoeRobich were doing some investigation of build failures in https://github.com/dotnet/roslyn-analyzers/pull/5772 and https://github.com/dotnet/roslyn-analyzers/pull/5674. I'm not sure if those failures are still blocking the merge?

Just as a reminder we are decommissioning old pools tomorrow (February 1, 2022) so any jobs using old pools won't run after this date.

**Comment by JoeRobich** [comment]
@lpatalas https://github.com/dotnet/roslyn-analyzers/pull/5772 has merged. Closing this out.

**Pull request closed without merging**
