### PR TITLE
Add CA1514: Remove redundant length argument

### PR DESCRIPTION
**Pull request by mpidash**
Fixes dotnet/runtime#68946.

This analyzer detects uses of `Substring/Slice(start, length)` that slice to the end of the buffer.
In these cases, the length check is redundant, can be omitted, and the call can be replaced with `Substring/Slice(start)`.
The analyzer also detects if the evaluation of the instance or arguments can lead to side effects and does not flag these cases.

I have found no warning when running the analyzer against `dotnet/runtime` and `dotnet/roslyn-analyzers`, 1 warning in `dotnet/roslyn` and 8 warnings in `dotnet/aspnetcore`:

1. [ContainedLanguageCodeSupport.cs(427,38): info CA1514: 'string.Substring(int, int)' uses a length check that can be avoided](https://github.com/dotnet/roslyn/blob/bb263ef6ac758aed10c277beb8a0f52e281d7574/src/VisualStudio/Core/Def/Venus/ContainedLanguageCodeSupport.cs#L427)
2. [EmbeddedFileProvider.cs(95,23): info CA1514: 'string.Substring(int, int)' uses a length check that can be avoided](https://github.com/dotnet/aspnetcore/blob/725a51ca03da787e76155fab501ca7b5e064479d/src/FileProviders/Embedded/src/EmbeddedFileProvider.cs#L95)
3. [RoutePatternParserTests.cs(112,17): info CA1514: 'string.Substring(int, int)' uses a length check that can be avoided](https://github.com/dotnet/aspnetcore/blob/725a51ca03da787e76155fab501ca7b5e064479d/src/Framework/AspNetCoreAnalyzers/test/RouteEmbeddedLanguage/RoutePatternParserTests.cs#L112)
4. [MultipartReader.cs(124,25): info CA1514: 'string.Substring(int, int)' uses a length check that can be avoided](https://github.com/dotnet/aspnetcore/blob/725a51ca03da787e76155fab501ca7b5e064479d/src/Http/WebUtilities/src/MultipartReader.cs#L124)
5. [AsciiDecoding.cs(108,78): info CA1514: 'System.Span<byte>.Slice(int, int)' uses a length check that can be avoided](https://github.com/dotnet/aspnetcore/blob/725a51ca03da787e76155fab501ca7b5e064479d/src/Servers/Kestrel/Core/test/AsciiDecoding.cs#L108)
6. [AsciiDecoding.cs(109,75): info CA1514: 'string.Substring(int, int)' uses a length check that can be avoided](https://github.com/dotnet/aspnetcore/blob/725a51ca03da787e76155fab501ca7b5e064479d/src/Servers/Kestrel/Core/test/AsciiDecoding.cs#L109)
7. [Program.cs(465,69): info CA1514: 'string.Substring(int, int)' uses a length check that can be avoided](https://github.com/dotnet/aspnetcore/blob/725a51ca03da787e76155fab501ca7b5e064479d/src/Servers/Kestrel/stress/Program.cs#L465)
8. [Utf8BufferTextWriter.cs(199,23): info CA1514: 'System.Memory<byte>.Slice(int, int)' uses a length check that can be avoided](https://github.com/dotnet/aspnetcore/blob/725a51ca03da787e76155fab501ca7b5e064479d/src/SignalR/common/Shared/Utf8BufferTextWriter.cs#L199)
9. [Utf8BufferTextWriterTests.cs(381,20): info CA1514: 'System.Memory<byte>.Slice(int, int)' uses a length check that can be avoided](https://github.com/dotnet/aspnetcore/blob/725a51ca03da787e76155fab501ca7b5e064479d/src/SignalR/common/SignalR.Common/test/Internal/Protocol/Utf8BufferTextWriterTests.cs#L381)

Not sure about the resource strings, would appreciate any suggestions.

### CODE REVIEW

**Review by buyaa-n — APPROVED** [review]
Thanks you @mpidash, left a few comments, overall LGTM

**Comment by buyaa-n** [comment]
> I have found no warning when running the analyzer against `dotnet/runtime` and `dotnet/roslyn-analyzers`, 1 warning in `dotnet/roslyn` and 8 warnings in `dotnet/aspnetcore`:

Thanks for broad testing, all looks valid and worth fixing.

**Comment by mpidash** [comment]
Thanks for the review @buyaa-n, I've addressed your review, merged main, and rerun `msbuild pack`, PTAL :)

**Comment by mpidash** [comment]
Seems like `msbuild pack` does not add a trailing newline to `AnalyzerReleases.Unshipped.md`, I've added it manually.

**Pull request merged**
