### PR TITLE
Add a table to VERSIONING.md file to list the version of released pac…

### PR DESCRIPTION
**Pull request by mavasani**
…kages, Git commit tag and SHA at which we produced the packages that were published on nuget, and the list of published analyzer packages.

### CODE REVIEW

**Comment by mavasani** [comment]
@srivatsn @tmeschter @genlu @lgolding

**Comment by mavasani** [comment]
Screenshot below:

version_table

**Comment by mavasani** [comment]
NOTE: This information enables us to service specific analyzer package(s) in future without having to maintain a separate branch for each release for any analyzer package. One would just create a separate branch off the Git commit SHA of the release, fix the bug and generate and publish the signed package from the branch.

**Comment by tmeschter** [comment]
LGTM

**Comment by genlu** [comment]
:+1:

**Pull request merged**
