### PR TITLE
Update documentation files in the repo

### PR DESCRIPTION
**Pull request by mavasani**
Auto-updated with following commands:
1. `msbuild /m /v:m /t:pack RoslynAnalyzers.sln`
2. `msbuild /m /v:m /t:pack FxCopAnalyzers.sln`

### CODE REVIEW

**Comment by Evangelink** [comment]
@mavasani Are you reviewing the issues found to check they all make sense? Do you create some tickets to fix (if that makes sense) the issues found?

**Comment by mavasani** [comment]
> Are you reviewing the issues found to check they all make sense? Do you create some tickets to fix (if that makes sense) the issues found?

@Evangelink I did not manually verify that analyzers _not_ listed from this tool have valid documentation at the link, the added tooling just verified that a webrequest at analyzer's helpLinkUri succeeds. I did manually verify that for all the CA analyzers listed as having missing documentation, attempting to navigate to help link  generates a 404 error and the documentation page indeed does not exist. I plan on creating issues for these and will post the issue links here soon.

**Comment by mavasani** [comment]
@Evangelink Sorry, I misunderstood your last comment and accidentally thought it was in context of another PR (#3539).

Regarding the changes in this PR - I did skim through the changed values and they seem reasonable to me. We will probably do another pass through the md/sarif files before publishing the package.

**Comment by Evangelink** [comment]
No worries, the info in your first comment are valuable :) I was curious to see if you were reviewing the issues manually or if you had some tool that would let you see/track the state of issues. For example, if you think that issue A is a FP, you somehow mark it as such and on some next update you could track if it goes away (fix/side-effect of a change...).

**Pull request merged**
