### PR TITLE
EquatableAnalyzer: We must override the base class Equals

### LINKED ISSUE #3983: False positive for CA1067
### Describe the bug

Related to #2027 
Base class implements `Equals(object)` and `IEquatable<BaseClass>`. 
Derived class overrides `IEquatable<BaseClass>`. It should not have to override `Equals(object)`.

### Steps To Reproduce

    public abstract class BaseClass : IEquatable<BaseClass>
    {
        public abstract bool Equals([AllowNull] BaseClass other);

        public sealed override bool Equals(object obj)
        {
            return Equals(obj as BaseClass);
        }
    }

    public class DerivedClass : BaseClass, IEquatable<DerivedClass>
    {
        public override bool Equals([AllowNull] BaseClass other)
        {
            return Equals(other as DerivedClass);
        }

        public bool Equals([AllowNull] DerivedClass other)
        {
            return true;
        }
    }

    internal sealed class TestEquals
    {
        [Test]
        public void EqualsObject()
        {
            var instance1 = new DerivedClass();
            var instance2 = new DerivedClass();

            Assert.That(Equals(instance1, instance2), Is.True);
        }
    }

### Expected behavior

CA1067 is not raised for `DerivedClass`

### Actual behavior

CA1067 is raised for `DerivedClass`

### Analyzer

**Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.0.0 (Latest)

**Diagnostic ID**: [CA1067](https://docs.microsoft.com/visualstudio/code-quality/ca1067)

### PR DESCRIPTION
**Pull request by manfred-brands**
Checks if either `Equals(object)` or `Equals(base)` is overridden in a derived class.

Fixes #3983

### CODE REVIEW

**Comment by b-a-roberts** [comment]
This update would help resolve with similar issues we see.

**Review by mavasani — CHANGES_REQUESTED** [review]
Please retarget this PR to https://github.com/dotnet/roslyn-analyzers/tree/release/6.0.1xx-preview1

**Comment by manfred-brands** [comment]
> Please retarget this PR to https://github.com/dotnet/roslyn-analyzers/tree/release/6.0.1xx-preview1

Rebased code on master.

**Comment by manfred-brands** [comment]
@mavasani I ran `test.cmd` locally without any issues. The reported failing lines is under a section '_Only run validate only in CI builds._'
Any suggestions?

**Comment by manfred-brands** [comment]
I compiled and ran the `GenerateDocumentationAndConfigFiles` tool manually to get the actual error not shown in the build. It complains that an "auto generated file wasn't updated".
This should either be added to the Build.cmd or at least to README as step 7 in case of new rules.

**Comment by manfred-brands** [comment]
@mavasani Created associate PR to update documentation under: https://github.com/dotnet/docs/pull/21838

**Comment by manfred-brands** [comment]
Rebased code again. Note that the documentation is already live, but the rule hasn't been merged in.

**Comment by mavasani** [comment]
> Note that the documentation is already live, but the rule hasn't been merged in.

That is unfortunate, especially given no one has yet approved the new rule or reviewed this PR. @gewarren, in future we may want to ensure that docs PR for new CA or IDE rule is not merged until the analyzer PR is merged in. I will review this PR later today.

**Review by mavasani — CHANGES_REQUESTED** [review]
Marking as blocked based on https://github.com/dotnet/roslyn-analyzers/issues/3983#issuecomment-748257032. If the issue is approved, I can remove my block and get the PR reviewed.

**Comment by mavasani** [comment]
Closing the PR based on the design discussion in https://github.com/dotnet/roslyn-analyzers/issues/3983

**Pull request closed without merging**
