### PR TITLE
Fix: NRE on static properties

### LINKED ISSUE #998: NRE in Desktop.Analyzers.CSharpDoNotUseInsecureDTDProcessingAnalyzer
See https://github.com/dotnet/roslyn-analyzers/issues/855#issuecomment-217141251

### PR DESCRIPTION
**Pull request by bkoelman**
Fixes #998.

### CODE REVIEW

**Comment by basoundr** [comment]
@bkoelman Could you please add a test?

**Comment by bkoelman** [comment]
I've added a test.

**Comment by mavasani** [comment]
👍

**Comment by mavasani** [comment]
@basoundr Can you merge if it looks good to you too?

**Comment by basoundr** [comment]
:+1:

**Pull request merged**
