### PR TITLE
Move interop services analyzers over

### PR DESCRIPTION
**Pull request by genlu**
- Copy System.Runtime.InteropServices.Analyzers over from dotnet/roslyn repo.
- Update package and target references.
- Fix build errors in SystemRuntimeInteropServicesAnalyzersTest.
- Add NuGet authoring project for System.Runtime.InteropServices.Analyzers

@tmeschter @srivatsn @mavasani

### CODE REVIEW

**Comment by srivatsn** [comment]
:+1:

**Comment by sharwell** [comment]
I think there is a better way to handle the NuGet packaging.. one sec.

**Comment by tmeschter** [comment]
@sharwell We're open to other suggestions for producing NuGet packages. The current setup isn't great, but it works.

**Comment by tmeschter** [comment]
:+1:

**Comment by sharwell** [comment]
In StyleCopAnalyzers, we use [Tvl.NuGet.BuildTasks](https://www.nuget.org/packages/Tvl.NuGet.BuildTasks/1.0.0-alpha002). You can see how it was incorporated in DotNetAnalyzers/StyleCopAnalyzers#521. It causes the package to be created during a normal C# project build. :+1:

**Comment by genlu** [comment]
@dotnet-bot Retest this, please.

**Comment by genlu** [comment]
@sharwell Thanks for the suggestion, I will take a look.

**Pull request merged**
