### PR TITLE
Fixed compiler errors in Desktop.Analyzers.UnitTests

### PR DESCRIPTION
**Pull request by bkoelman**

### CODE REVIEW

**Comment by bkoelman** [comment]
It looks like cibuild does not start. Can anyone check?

**Comment by mavasani** [comment]
👍

**Comment by bkoelman** [comment]
One test I could not fix. It fails with message that /unsafe compiler switch is needed. 

Since `VerifyCSharp(...)` has no parameter to pass extra compiler options, would it be okay to enable the unsafe switch globally (for all tests in the repository)?

**Comment by mavasani** [comment]
> would it be okay to enable the unsafe switch globally (for all tests in the repository)

I would rather have different VerifyXXX overload that takes compilation options - you can probably create a separate test work item for it and leave the test as is for now.

**Comment by bkoelman** [comment]
Okay I'll save that for another time.

**Pull request merged**
