### PR TITLE
CA1826 fixer support for vb

### PR DESCRIPTION
**Pull request by TKharaishvili**
Related to the issue - https://github.com/dotnet/roslyn-analyzers/issues/1932

### CODE REVIEW

**Comment by TKharaishvili** [comment]
@genlu so the initial implementation was C# specific but I now figured out a way to make it work for VB too. Split it into separate commits. I hope that'll make it easier for you to review it.

**Comment by genlu** [comment]
@TKharaishvili Thanks! I will review this once I have time.

**Comment by mavasani** [comment]
@TKharaishvili Would you be able to resolve the conflicts please?

**Comment by TKharaishvili** [comment]
@mavasani I see that much of the fixer has been updated. Do you want me to just resolve the conflicts? Or update my code to mimic the new style as well?

**Comment by mavasani** [comment]
@TKharaishvili What did you mean by new style? Are you referring to the code fix tests, which have been moved to a new test framework? If so, you should make sure that the tests are still using the new test framework.

**Comment by mavasani** [comment]
Ping @TKharaishvili

**Comment by TKharaishvili** [comment]
@mavasani sorry for not being able to answer quicker, I wasn't around. I'll get to this in the next couple of days.

**Comment by TKharaishvili** [comment]
Alright @mavasani there you go.

**Comment by genlu** [comment]
@mavasani So master is 2.9.x now, right? I assume this is what you want?

**Comment by mavasani** [comment]
@genlu Yes

**Pull request merged**
