### PR TITLE
Switch to 1ES R&D pools on main

### PR DESCRIPTION
**Pull request by jonfortescue**
Per https://github.com/dotnet/core-eng/issues/14276.

cc/ @lpatalas @ulisesh

### CODE REVIEW

**Comment by jmarolf** [comment]
@jonfortescue can you add this to the pipeline: https://github.com/dotnet/roslyn-sdk/blob/9e0d174c165bccdc18f8231c4268b1a19f2be420/.vsts-pr.yaml#L52-L55

so we can get dumps of what is happening?

**Comment by jonfortescue** [comment]
@jmarolf added.

**Comment by jonfortescue** [comment]
@jmarolf does it look like we have the logs?

**Review by JoeRobich — APPROVED** [review]

**Pull request closed without merging**
