### PR TITLE
Cleanup tests for CA2200 (RethrowToPreserveStackDetails)

### LINKED ISSUE #1016: Broken tests (and possibly analyzer) for CA2200
#### Analyzer package
Microsoft.QualityGuidelines.Analyzers

#### Analyzer
CA2200: RethrowToPreserveStackDetailsAnalyzer

The code in test https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.QualityGuidelines.Analyzers/UnitTests/RethrowToPreserveStackDetailsTests.cs#L69 contains several compile errors:

```csharp
01 using System;
02 
03 class Program
04 {
05     void CatchAndRethrowExplicitly()
06     {   
07         try
08         {
09             try
10             {
11                 throw new ArithmeticException();
12             }
13             catch (ArithmeticException e)
14             {
15                 throw;
16             }
17             catch (ArithmeticException)
18                 try
19                 {
20                     throw new ArithmeticException();
21                 }
22                 catch (ArithmeticException i)
23                 {
24                     throw e;
25                 }
26             }
27         }
28         catch (Exception e)
29         {
30             throw;
31         }
32     }
33 }
```

* line 17: CS1514 { expected
* line 24: CS0103 The name 'e' does not exist in the current context
* line 17: CS0160 A previous catch clause already catches all exceptions of this or of a super type ('ArithmeticException')

Fixing any of these errors causes the analyzer under test to start emitting warnings, while the test expects no warnings. Of course the broken code could be intentional, but based on the test name CA2200CSharpTestWithLegalExceptionThrowNested that seems unlikely.

Often it helps to look at [the related VB test](CA2200VisualBasicTestWithLegalExceptionThrowNested). But that one has its own compiler errors, so I'm lost on how to resolve these.

Are only these tests broken, or is the analyzer too?

### PR DESCRIPTION
**Pull request by bkoelman**
* Renamed tests to make their purpose easier to understand
* Merged separate test sets for CS/VB into single tests that contain both languages
* Re-enabled skipped test with compile errors

Fixes #1016.

### CODE REVIEW

**Comment by bkoelman** [comment]
@jmarolf Please review, especially the one with compile errors. Is this what you meant?

**Comment by jmarolf** [comment]
@bkoelman test looks good, but why combine VB and C# into a single test for each scenario?  The VB and C# implementations are different.  If I make a change and break a test I want the smallest possible scenario of what broke.

**Comment by bkoelman** [comment]
I combined them in the process of trying to understand the purpose of all
the individual tests. Without looking at how the analyzers were
implemented. Now that their names better reflect the scenarios, I'd be
happy to split them again. Note however that many other tests in the repro
are combined in the same way, so I did not think splitting them to be
important. Still I would prefer to have the VB/C# versions side-by-side per
scenario, instead of all C# tests first, followed by all VB tests. Would
that be okay for you?

**Comment by jmarolf** [comment]
:+1: If this matches the other tests

**Pull request merged**
