### PR TITLE
Update BannedApiAnalyzers.Help.md

### PR DESCRIPTION
**Pull request by AndreasVolkmann**
Small typos

### CODE REVIEW

**Comment by ltrzesniewski** [comment]
Note that this will conflict with #5240 (if it ever gets merged).

**Comment by Evangelink** [comment]
Hi @AndreasVolkmann, are you willing to update your PR?

**Comment by ltrzesniewski** [comment]
@Evangelink the typos have been corrected in my PR actually (as I needed to change the sentences anyway).

**Comment by Evangelink** [comment]
Thanks for the info @ltrzesniewski 

@mavasani I am closing the PR.

**Pull request closed without merging**
