### PR TITLE
Port remaining FxCop rules

### PR DESCRIPTION
**Pull request by reflectronic**
This PR is about porting [the remaining FxCop rules](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-rule-port-status#rules-that-may-be-ported) to the Roslyn-based code analysis package. I am pretty new to Roslyn (let alone this codebase), so please excuse any noob mistakes or questions, but so far I feel like most things have been done right 😄

Right now I've only ported about 20 rules (with tests for all of them), but I'm planning to port most of the rules on the list in the end. For now, I want to just make a pass across all of the remaining diagnostics to port first before I start writing code fixers. In addition, I've added a new little test utility that makes it easier to test analyzers that should only report at a certain accessibility (like many of the ones I ported, which only report when the member in question is exposed outside of the assembly).

I have a few questions so far about implementing some of these rules:
- [CA1045: Do not pass types by reference](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1045-do-not-pass-types-by-reference). The official documentation states that: <blockquote>A public or protected method in a public type has a `ref` parameter that takes a primitive type, a reference type, or a value type that is not one of the built-in types.</blockquote> However, I can't really make sense of which types it is exactly talking about — until someone can clarify this, right now the analyzer just warns for every `ref` parameter.
- [CA1403: Auto layout types should not be COM visible](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1403-auto-layout-types-should-not-be-com-visible). The official documentation documentation says: <blockquote>To reduce false positives, this rule requires the COM visibility of the type to be explicitly stated. The containing assembly must be marked with the `System.Runtime.InteropServices.ComVisibleAttribute` set to false and the type must be marked with the ComVisibleAttribute set to true.</blockquote> However, the rationale for this decision... <blockquote>If the `StructLayoutAttribute` attribute is not specified, the C#, Visual Basic, and C++ compilers specify `LayoutKind.Auto` for value types.</blockquote> is [wrong](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.structlayoutattribute#remarks): <blockquote>C#, Visual Basic, and C++ compilers apply the `Sequential` layout value to structures by default.</blockquote> Currently, I just haven't reimplemented this behavior. I think this is okay, especially considering my suggestion below, but if we need to do this for backwards compatibility that's OK.
- [CA1413: Avoid non-public fields in COM visible value types](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1413-avoid-non-public-fields-in-com-visible-value-types). I think we should take a different direction for this analyzer than to only enable it when the type is explicitly marked as `ComVisible`, as I think this can probably bite someone without them realizing it; maybe the COM-related analyzers should be disabled by default, and they can be enabled manually 'as a package' when people are *really* intending to expose themselves to COM? Or should we keep them, on but somehow try and indicate to people to consider the COM visibility of their assembly and whether they should disable it (I think the project templates turn COM visibility off right now anyway)?

Thank you guys for your time!

### CODE REVIEW

**Comment by mavasani** [comment]
@reflectronic Thank you for the contribution! We would review the ported rules this week and attempt to answer your questions. Would it be possible for you to break each rule port into a separate pull request? That would enable more traction in getting these merged in. Otherwise, it might just take more time to get the whole thing merged.

**Comment by sharwell** [comment]
@reflectronic I'll echo what @mavasani and add one thing: if there are any of these rules which you consider more urgent because your team wants to use them, please let us know so we can prioritize the reviews of those first. 👍

**Comment by reflectronic** [comment]
Alright, I’ll work on splitting up the PR 👍

**Comment by reflectronic** [comment]
Sorry for letting this PR languish for a little bit. I do most of my development work on macOS and, as far as I can tell, you can really only work on this project using Windows & I haven't had much time to work on this using a Windows machine. I'll have more time to work on it very soon.

Just one question — all of these analyzers (more specifically, the tests) depend on some new helper classes I added (e.g. making sure analyzers only report a diagnostic on public members). I assume the proper way to do that is to make a 'base' branch that has the code for these helpers and then each new analyzer branches from that 'base' branch. If that's not the proper/best way to do that, let me know of what I should do 😄

**Comment by mavasani** [comment]
> all of these analyzers (more specifically, the tests) depend on some new helper classes I added (e.g. making sure analyzers only report a diagnostic on public members). I assume the proper way to do that is to make a 'base' branch that has the code for these helpers and then each new analyzer branches from that 'base' branch. If that's not the proper/best way to do that, let me know of what I should do

Can you point me an example helper class in your PR? We already have an extension method to determine if a symbol is externally visible or not: https://github.com/dotnet/roslyn-analyzers/blob/828a75bdeb27a45d66e42308834616d78fcc24eb/src/Utilities/Compiler/Extensions/ISymbolExtensions.cs#L191-L195. Similarly, majority of the shared functionality between analyzers should already have extension methods. If you need to add some utilitiy helper classes shared between analyzers or projects in the solution, we normally add them to the shared project  [Analyzer.Utilities.shproj](https://github.com/dotnet/roslyn-analyzers/blob/master/src/Utilities/Compiler/Analyzer.Utilities.shproj).

I think the best approach here is to create a separate PR with just a single analyzer/fixer and we can iterate on the best design.

**Comment by reflectronic** [comment]
For example, I added :
```cs
public enum AccessibilityTestTarget
{
    Class,
    InsideClass,
}

public struct AccessibilityContext
{
    public string AccessVB => ; // get the accessibility's actual name in VB
    public string AccessCS => ; // get the accessibility's actual name in C#

    public string Left(bool useBrace = false, string id = null)
    {
        return useBrace ?
            ExpectDiagnostic ? $"{{|{id}:" : string.Empty :
            ExpectDiagnostic ? "[|" : string.Empty;
    }

    public string Right(bool useBrace = false)
    {
        return useBrace ?
            ExpectDiagnostic ? "|}" : string.Empty :
            ExpectDiagnostic ? "|]" : string.Empty;
    }

    public Accessibility Accessibility { get; }
    public bool ExpectDiagnostic { get; }
}

public class AccessibilityTestAttribute : DataAttribute
{
    public AccessibilityTestTarget Target { get; }

    public override IEnumerable<object[]> GetData(MethodInfo testMethod)
    {
        yield return new object[] { new AccessibilityContext(Accessibility.Public, expectDiagnostic: true) };
        yield return new object[] { new AccessibilityContext(Accessibility.Internal, expectDiagnostic: false) };

        // Non-nested classes can only have the above two visibilities
        if (Target == AccessibilityTestTarget.Class) yield break;

        // Yield the rest of the visibilities...
    }
}
```

It's used a little bit like this:
```cs
[Theory]
[AccessibilityTest(AccessibilityTestTarget.InsideClass)]
public async Task ListProperty_WarnsWhenExposed(AccessibilityContext ctx)
{
    await VerifyCS.VerifyAnalyzerAsync($@"
        public class Test
        {{
            {ctx.AccessCS} System.Collections.Generic.List<int> {ctx.Left()}Ints{ctx.Right()} => null;
        }}");

    await VerifyVB.VerifyAnalyzerAsync($@"
        Public Class Test
            {ctx.AccessVB} Property {ctx.Left()}Actions{ctx.Right()} As System.Collections.Generic.List(Of Integer)
        End Class");
}
```

That way I could test that only externally exposed list properties would report.

**Comment by tom-englert** [comment]
Any progress on this?

**Comment by mavasani** [comment]
@tom-englert Are you looking for any specific rule to be ported? Also tagging @Evangelink who has been helping port many FxCop rules to the FxCop analyzers package.

**Comment by reflectronic** [comment]
I haven't worked on this in a while, and frankly, 1) the code is not that good, and 2) a lot of these rules have already been implemented in the meantime. 

https://github.com/dotnet/roslyn-analyzers/pull/3273 is the blocker for me, personally. Hopefully, whenever that gets merged, I can continue working on some of the rules in here (like the COM ones).

**Comment by tom-englert** [comment]
@reflectronic I was missing `CA1006: Do not nest generic types in member signatures` and `CA1720: Identifiers should not contain type names` when I came across this.

**Comment by tom-englert** [comment]
@mavasani I was missing `CA1006: Do not nest generic types in member signatures` and `CA1720: Identifiers should not contain type names` when I came across this.

**Comment by Evangelink** [comment]
@tom-englert [CA1060](https://github.com/dotnet/roslyn-analyzers/issues/372). It seems that `CA1720` is implemented but the behavior might not be 100% right (see https://github.com/dotnet/roslyn-analyzers/issues/1147)

**Comment by tom-englert** [comment]
@Evangelink resolved it, the correct analyzer package was missing in some projects...

**Pull request closed without merging**
