### PR TITLE
Loc update

### PR DESCRIPTION
**Pull request by cristianosuzuki77**
Loc update

### CODE REVIEW

**Comment by Youssef1313** [comment]
Tagging @buyaa-n for test failures.

**Comment by wli3** [comment]
@sharwell could you look into the error and merge this?

**Comment by wli3** [comment]
@sharwell and this ships in SDK right? Could you make sure there is an insertion to SDK later with the loc change?

**Comment by buyaa-n** [comment]
> Tagging @buyaa-n for test failures.

Thanks, @Youssef1313, this was fixed before, but seems was not merged into `release/5.0.2xx` i will open PR into `release/5.0.2xx`

**Comment by buyaa-n** [comment]
PR https://github.com/dotnet/roslyn-analyzers/pull/4821

**Comment by mavasani** [comment]
@buyaa-n This PR should be merged or closed?

**Comment by wli3** [comment]
Please merge this once the branch is correct

**Comment by buyaa-n** [comment]
> @buyaa-n This PR should be merged or closed?

@mavasani the test failures fixed, this is ready for review and merge

**Review by buyaa-n — APPROVED** [review]
I don't see any non-localization related changes, i assume loc changes already reviewed so LGTM, merging

**Pull request merged**
