### PR TITLE
LOC CHECKIN | dotnet/roslyn-analyzers master | 20190321

### PR DESCRIPTION
**Pull request by v-zbsail**

### CODE REVIEW

**Comment by genlu** [comment]
@v-zbsail Could you please resolve the conflicts?

**Comment by v-zbsail** [comment]
> @v-zbsail Could you please resolve the conflicts? Thanks!

@genlu I've never dealt with the conflicts before so I don't know how to do it properly. I am not familiar with the content of the files as I just receive the localized versions and create the PR.

**Comment by genlu** [comment]
@tmeschter I have got the error below in CI, do you know how to fix it? I tried to set `UpdateXlfOnBuild` as suggested locally, but it doesn't work

>D:\j\workspace\Windows_NT_Re---c6b3d408\.packages\xlifftasks\0.2.0-beta-63004-01\build\XliffTasks.targets(92,5): error : 'Maintainability\xlf\MicrosoftMaintainabilityAnalyzersResources.cs.xlf' is out-of-date with 'Maintainability\MicrosoftMaintainabilityAnalyzersResources.resx'. Run `msbuild /t:UpdateXlf` to update .xlf files or set UpdateXlfOnBuild=true to update them on every build, but note that it is strongly discouraged to set UpdateXlfOnBuild=true in official/CI build environments as they should not modify source code during the build. [D:\j\workspace\Windows_NT_Re---c6b3d408\src\Microsoft.CodeQuality.Analyzers\Core\Microsoft.CodeQuality.Analyzers.csproj]

**Comment by tmeschter** [comment]
@genlu Pull v-zbsail:loc_20190321_master into your local repo, and try touching MicrosoftMaintainabilityAnalyzersResources.resx in your local repo to update the timestamp and build again. That should update the associated .xlf files, which you can then commit and push back to v-zbsail:loc_20190321_master.

There's a bug in xliff-tasks where we miss that a file is out-of-date when we go to update the .xlf, but we detect it later.

**Comment by tmeschter** [comment]
(I believe the bug has been fixed but the updated package hasn't propagated to dotnet/arcade yet)

**Comment by genlu** [comment]
@v-zbsail I have created a new 2.9.x branch, which will flow into master. So I retargeted this PR to 2.9.x instead.

**Comment by mmitche** [comment]
@dotnet-bot test this please

**Comment by genlu** [comment]
Hmm, after fixing all the issues, we ended up with no actual changes. Is this intended? @v-zbsail

**Comment by janbaltus** [comment]
this was first PR from new localization platform which verified onboarding was successfull.

**Pull request merged**
