### PR TITLE
Enable the running of tests in Test Explorer

### PR DESCRIPTION
**Pull request by davkean**
Fixes: #274

Upgraded to xunit 2.1, which enables us to turn off shadow copying via app.config.

Make note, this includes https://github.com/dotnet/roslyn-analyzers/pull/926, as its a dependency. Look at the last commit just to see what was actually changed.

### CODE REVIEW

**Comment by davkean** [comment]
tag @dotnet/roslyn-analysis

**Comment by davkean** [comment]
Restore failed because it's missing a commit from #926. When that's in this will succeed.

This is what Test Explorer now looks like for me:

image

**Comment by srivatsn** [comment]
:+1:

**Comment by davkean** [comment]
@dotnet-bot retest this please

**Pull request merged**
