### PR TITLE
Rename analyzers

### PR DESCRIPTION
**Pull request by genlu**
DotNetAnalyzers.BannedApiAnalyzer => Microsoft.CodeAnalysis.BannedApiAnalyzer
DotNetAnalyzers.PublicApiAnalyzer =>  Microsoft.CodeAnalysis.PublicApiAnalyzer 
Microsoft.PerformanceSensitive.Analyzers =>  Microsoft.CodeAnalysis.PerformanceSensitive.Analyzers

### CODE REVIEW

**Comment by genlu** [comment]
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(114,5): error : The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [D:\j\workspace\Windows_NT_De---ec62cf09\RoslynAnalyzers.sln]

Hmm, any idea how to solve this issue, other than shorten the name?

**Comment by mavasani** [comment]
Is this just the `.Package.csproj` project? You can probably just rename it to exclude the Microsoft.CodeAnalysis prefix and try.

**Comment by mavasani** [comment]
Also tagging @AArnott

**Comment by mavasani** [comment]
@genlu We should merge public API analyzer and fix into the same project. Talk to @sharwell for background. Please revert the last commit.

**Comment by genlu** [comment]
@mavasani OK, will do. I merged them only because the path too long error. Guess I have to shorten the folder name instead.

@sharwell Why they can't be merged into one? Does the codefix relies on workspace?

**Comment by AArnott** [comment]
> @sharwell Why they can't be merged into one? Does the codefix relies on workspace?

Yes, that's the problem. Having one project include codefixes requires that it references assemblies that analyzers mustn't ever require to be present or they'll fail in some cmdline builds. It's too hard to avoid dependencies creeping into analyzers that depend on Workspaces when a reference exists.

**Pull request merged**
