### PR TITLE
Loc Checkin 9/30/2020

### PR DESCRIPTION
**Pull request by cristianosuzuki77**
Latest translations.

### CODE REVIEW

**Comment by wli3** [comment]
@Youssef1313 @mavasani could you merge the loc pass?

**Comment by Youssef1313** [comment]
@wli3 I'm an external contributor, so don't have access to merge.

**Comment by mavasani** [comment]
@buyaa-n Seems like PlatformCompatibility analyzer tests are failing in Spanish run after localizing resource strings. Can you please prioritize fixing these? If you need more time, we should skip the failing tests in this PR and file a follow-up issue to fix and unskip them.

https://dev.azure.com/dnceng/public/_build/results?buildId=837957&view=ms.vss-test-web.build-test-results-tab&runId=26687216&resultId=101806&paneView=debug

**Comment by Youssef1313** [comment]
@mavasani I'll give it a look now and open a fix PR.

**Comment by buyaa-n** [comment]
Thanks, @mavasani @Youssef1313, the PR is ready for review https://github.com/dotnet/roslyn-analyzers/pull/4267

**Review by mavasani — APPROVED** [review]

**Pull request merged**
