### PR TITLE
Use CancellationToken whenever possible

### PR DESCRIPTION
**Pull request by Youssef1313**
By manually going through the code, I found there are places where CancellationToken can be used but not actually used. There are more places than this PR, I opened this to get a review on whether I should continue on that or not.

### CODE REVIEW

**Comment by mavasani** [comment]
@Youssef1313 I think it is better to wait for @carlossanlop to merge in https://github.com/dotnet/roslyn-analyzers/pull/3641 and use the added analyzer/fixer to drive and enforce these.

**Comment by Youssef1313** [comment]
The new analyzer will find **some** occurrences, not all.
So, I think I should wait, and after the analyzer is shipped and fixes what it can, I start on the non-captured occurrences in this PR.

What do you think? @mavasani

**Comment by mavasani** [comment]
@Youssef1313 Thanks, that sounds good. I can even merge this PR if you'd like, and you can create a new PR after the analyzer/fixer is merged. Whatever you prefer.

**Comment by Youssef1313** [comment]
I'm okay in both cases :)

**Comment by mavasani** [comment]
I'll merge given this is ready! :)

**Pull request merged**
