### PR TITLE
Move analyzers repo to Microsoft.CodeAnalysis 1.3 packages

### PR DESCRIPTION
**Pull request by mavasani**

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @dotnet/roslyn-analysis

**Comment by srivatsn** [comment]
👍

**Comment by srivatsn** [comment]
Actually should we do this? Don't we want to keep working on 1.2 so that min requirement is Update 2?

**Comment by mavasani** [comment]
Why? Everyone should move to Update3 now, especially if consuming 1.3.0-betaXXX analyzer packages (https://github.com/dotnet/roslyn-analyzers/pull/1059).

Additionally, this is needed to make fixes that depend on MS.CA 1.3 packages: https://github.com/dotnet/roslyn-analyzers/issues/983, https://github.com/dotnet/roslyn-analyzers/issues/999, etc.

**Comment by mavasani** [comment]
We have decided that until we need a new API from future Microsoft.CodeAnalysis packages, we will compile the analyzers repo against 1.2 package.

**Pull request closed without merging**
