### PR TITLE
Normalize multiline descriptions to \n in sarif files

### LINKED ISSUE #4587: GenerateDocumentationAndConfigFiles does not work on linux
The tool located [here](https://github.com/dotnet/roslyn-analyzers/tree/master/src/Tools/GenerateDocumentationAndConfigFiles) relies on windows specific line endings to work correctly and was disabled in linux builds in https://github.com/dotnet/roslyn-analyzers/pull/4444. We should fix this and enable validation on linux builds

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes #4587

cc: @Evangelink

### CODE REVIEW

**Comment by sharwell** [comment]
Can we enable the tool in Linux builds again?

**Comment by Youssef1313** [comment]
> Can we enable the tool in Linux builds again? Should be a good indicator of whether we fixed all the cases.

Ah yes. I forgot. That's the main goal of the PR 😄

**Comment by jmarolf** [comment]
as @sharwell says, If you can remove all the uses of [WindowsOnlyFact](https://grep.app/search?q=WindowsOnlyFact&filter[repo][0]=dotnet/roslyn-analyzers) I'll sign off

**Comment by Youssef1313** [comment]
> as @sharwell says, If you can remove all the uses of [WindowsOnlyFact](https://grep.app/search?q=WindowsOnlyFact&filter%5Brepo%5D%5B0%5D=dotnet/roslyn-analyzers) I'll sign off

That's a different issue tracked by https://github.com/dotnet/roslyn-analyzers/issues/4586. I'm planning to look into it, but maybe should be in a different PR

**Comment by jmarolf** [comment]
ah, right you are

**Review by sharwell — APPROVED** [review]

**Pull request merged**
