### PR TITLE
Remove unused project

### PR DESCRIPTION
**Pull request by Evangelink**
From https://github.com/dotnet/roslyn-analyzers/pull/5729#discussion_r753639824

### CODE REVIEW

**Review by Youssef1313 — APPROVED** [review]

**Comment by Evangelink** [comment]
@Youssef1313 Sorry! I missed your review and force-pushed afterward...

**Review by Youssef1313 — APPROVED** [review]
Is the whole `tools` folder not used? We can fully delete it if that's the case.

**Comment by mavasani** [comment]
@jmarolf do you know if anything inside tools folder is used? I don’t recall any usage.

**Comment by Evangelink** [comment]
I have run a global search on the repo and I couldn't find any match so I'd say it seems safe to remove. I will wait for the green-light from @jmarolf

**Review by jmarolf — APPROVED** [review]
Thanks for removing this. I am not aware of any usage for this code. this is just more complexity for new contributors

**Pull request merged**
