### PR TITLE
Address comments of CA1311 (Use ToLowerInvariant/ToUpperInvariant) PR

### PR DESCRIPTION
**Pull request by Youssef1313**
Follow-up to #2186

@buyaa-n Two of the new tests are failing. I can't address the failure before the next week. Feel free to take over the PR if you (or @TKharaishvili) want to.

Commit by commit review is recommended.

### CODE REVIEW

**Comment by buyaa-n** [comment]
Thanks @Youssef1313  for finding the typo and the bug  

@TKharaishvili could take a look and contribute for the fix?

**Comment by TKharaishvili** [comment]
Hi @buyaa-n, can't do it in the near future unfortunately. Maybe a week or two from now but not before. Would that work?

**Comment by buyaa-n** [comment]
> Maybe a week or two from now but not before. Would that work?

2-3 weeks sounds good, the bug and typo is not critical, so need an urgency, thanks!

**Comment by TKharaishvili** [comment]
@Youssef1313 @buyaa-n I'm a bit confused here. Is it possible to add contributions to existing PR's?
If I open up a new PR the existing contributions here will be lost...

**Comment by Youssef1313** [comment]
@TKharaishvili I'm totally okay with a new PR and discarding this one.

**Comment by TKharaishvili** [comment]
@buyaa-n @Youssef1313 here's the new PR - https://github.com/dotnet/roslyn-analyzers/pull/6010

**Pull request closed without merging**
