### PR TITLE
Move the analyzers repo to Microsoft.CodeAnalysis 1.2.0 bits and turn…

### PR DESCRIPTION
**Pull request by mavasani**
… on the IOperation Feature flag while running our unit tests.

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @dotnet/roslyn-analysis for review

**Comment by mavasani** [comment]
FYI: Initially I was thinking that we need to move to 1.2.1, but that would mean the analyzers cannot be run on VS2015 Update2 build which has version 1.2.0 of MS.CA binaries.

**Comment by srivatsn** [comment]
The assembly version of the 1.2.1 package should still be 1.2.0.0 right? Not saying we should move to 1.2.1 - I believe there's nothing between those that's important to us.

**Comment by mavasani** [comment]
Ah, I guess you are right, but there is just an EnC fix in 1.2.1, so I also agree we should be fine with moving to just 1.2.0.

**Comment by srivatsn** [comment]
:+1:

**Pull request merged**
