### PR TITLE
Solution/assembly refactoring and move to latest Microsoft.CodeAnalysis.Analyzers

### PR DESCRIPTION
**Pull request by mavasani**
1. https://github.com/dotnet/roslyn-analyzers/commit/516a1e72bde8c27e9b93d8c58133228a28416a75: Move to latest Microsoft.CodeAnalysis.Analyzers and fix issues related to FixAllProvider in fixers

2. https://github.com/dotnet/roslyn-analyzers/commit/9d3cf58860a08d25bd9e8ff9a12d5a55a30d1b2b: Make Analyzer.Utilities a shared project and make utilities internal. This should improve performance by avoiding extra assembly load for a small set of utility helpers.

I was planning to do 2. as a separate PR, but https://github.com/dotnet/roslyn-analyzers/issues/1413#issuecomment-347934446 was causing lot of false positives, so I added the commit to this PR to avoid adding suppressions and then remove it again.

### CODE REVIEW

**Comment by heejaechang** [comment]
so issue was these fixer not supporting fix all?

**Comment by mavasani** [comment]
Yes, bunch of them were not supporting it, some were registering multiple different code actions but using same equivalence key so FixAll would incorrectly try to invoke all of them, etc. Now all fixers that register at least one fix will be required to override GetFixAllProvider and make an explicit decision to support FixAll or not. Also code actions must supply a non-null equivalence key (RS1011).

**Comment by mavasani** [comment]
Ping, any other feedback? I would like to get this into our preview package release.

**Comment by mavasani** [comment]
Thank you @heejaechang

**Comment by jinujoseph** [comment]
LGTM  (late review )

**Pull request merged**
