### PR TITLE
Fix couple of analyzer bugs

### LINKED ISSUE #940: CA2222 (DoNotDecreaseInheritedMemberVisibility) fires on members with resultant accessiblity private/internal
#### Repro steps

1. Open Analyzers.sln
2. Change Dependencies\CodeAnalysis\project.json to include: `"Microsoft.CodeAnalysis.FxCopAnalyzers": "1.2.0-beta1"`
3. Restore NuGet packages for solution
4. Remove CA2222 suppression added to build\Rulesets\Analyzers.ruleset (if any)
5. Open Analyzer.Utilities\Extensions\IEnumerableOfIMethodSymbolExtensions.cs
6. Goto line 138, for the ctor of the following class definition:

```
// Contains the expected properties of a parameter
    public class ParameterInfo
    {
        public int ArrayRank { get; private set; }
        public bool IsArray { get; private set; }
        public bool IsParams { get; private set; }
        public INamedTypeSymbol ParameterType { get; private set; }

        private ParameterInfo(INamedTypeSymbol type, bool isArray, int arrayRank, bool isParams)
        {
            ParameterType = type;
            IsArray = isArray;
            ArrayRank = arrayRank;
            IsParams = isParams;
        }

        public static ParameterInfo GetParameterInfo(INamedTypeSymbol type, bool isArray, int arrayRank, bool isParams)
        {
            return new ParameterInfo(type, isArray, arrayRank, isParams);
        }
    }
```

#### Expected Behavior
We shouldn't be firing this warning on members that have resultant visibility != Public. Seems like this analyzer is implementing its own logic for IsVisibleOutsideAssembly instead of using the helper in AnalyzerUtilities.

#### Actual Behavior
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA2222	Do not decrease inherited member visibility	Analyzer.Utilities	C:\roslyn-analyzers\src\Analyzer.Utilities\Extensions\IEnumerableOfIMethodSymbolExtensions.cs	138	Active
```

### LINKED ISSUE #949: TypeNamesShouldNotMatchNamespaces (CA1724) reports on WinForms designer-generated code
#### Analyzer package
Microsoft.ApiDesignGuidelines.Analyzers

#### Analyzer
CA1724: TypeNamesShouldNotMatchNamespaces

#### Repro steps
1. Create a WinForms application
2. Open Project properties > Resources and add a string resource
3. `install-package Microsoft.ApiDesignGuidelines.Analyzers -pre`
4. CA1724 reported on generated code in `Resources.Designer.cs`:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CA1724	The type name Resources conflicts in whole or in part with the namespace name 'System.Resources' defined in the .NET Framework. Rename the type to eliminate the conflict.	WindowsFormsApplication1	e:\bart\documents\visual studio 2015\Projects\WindowsFormsApplication1\WindowsFormsApplication1\Properties\Resources.Designer.cs	25	Active
```

#### Expected behavior
No reporting on designer-generated code.

#### Actual behavior
Above repro reports CA1724.

### PR DESCRIPTION
**Pull request by mavasani**
1. Fix DoNotDecreaseInheritedMemberVisibilityAnalyzer to match few more cases with binary FxCop 
Fixes #940

2. Fix TypeNamesShouldNotMatchNamespacesAnalyzer to not report analyze/report diagnostics on generated code.
Fixes #949
Seems like invoking `analysisContext.ConfigureGeneratedCodeAnalysis(GeneratedCodeAnalysisFlags.Analyze)`, which should suppress all diagnostics on generated code, still allows the analyzer to report compilation end diagnostics on generated code. I'll file a separate bug on roslyn repo to fix the driver.

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @dotnet/roslyn-analysis for review

**Comment by srivatsn** [comment]
👍

**Comment by bkoelman** [comment]
@mavasani Did you already file a separate bug on roslyn repo to fix the driver?

I have looked around in the source of [AnalyzerDriver](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.cs) / [AnalyzerExecutor](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerExecutor.cs,81264a14cf12c287) and believe there is no easy way to get this working. 

`SymbolAnalysisContext.ReportDiagnostic()` does not receive the symbol it applies to. But it is always executed as a result of analyzing a known symbol (the one in SymbolAnalysisContext object). That known symbol is then checked for whether it comes from generated code, not the actual symbol on which a diagnostic is reported.

`CompilationAnalysisContext.ReportDiagnostic()` also does not receive the symbol it applies to, only the (first?) location (which is optional). As it may report anything from the compilation, it's not clear which source symbol/node/operation/... should be checked for whether it comes from generated code.

So I don't see an obvious way for the driver/executor to determine whether a symbol, syntax node, tree or operation comes from generated code in the Compilation End analysis.

**Comment by mavasani** [comment]
@bkoelman I'll file it now. Note that we do the generated code filtering for reported diagnostics based on its primary location, not based on what context it was reported. See this method: http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerDriver.cs,303.

We just need to fix [this](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerExecutor.cs,1276) method to add [this](http://source.roslyn.io/#Microsoft.CodeAnalysis/DiagnosticAnalyzer/AnalyzerExecutor.cs,1318) if check to do this filtering for compilation diagnostics, we seem to be doing it only for non-compilation diagnostics.

**Comment by mavasani** [comment]
Opened https://github.com/dotnet/roslyn/issues/11217

**Comment by bkoelman** [comment]
@mavasani Yes you are correct. I see now how I got on the wrong track by looking at `isGeneratedCode` parameter. The primary location is actually used for source.

**Pull request merged**
