### PR TITLE
Fix PublicAPI code fix to avoid duplicate entries from FixAll operations

### LINKED ISSUE #2195: PublicApiAnalyzer Fix All duplicate entries for partial types
#### Analyzer package

Example: DotNetAnalyzers.PublicApiAnalyzer

#### Package Version

Example: 2.9.0-beta1.19162.2+321600d1

#### Repro steps

Tested in Visual Studio 2017 version 15.9.8.

1. Create a public partial type with parts in multiple files
1. Delete the contents of the Public API files
1. Apply a Fix All operation to add all the missing APIs

#### Expected behavior

The partial type appears once in PublicAPI.Unshipped.txt.

#### Actual behavior

The partial type appears once in PublicAPI.Unshipped.txt for each part.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #2195

### CODE REVIEW

**Comment by mavasani** [comment]
Thanks!

**Comment by RussKie** [comment]
Thank you

It is not yet on https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers. When will it be available for consumption?

**Comment by mavasani** [comment]
Please try https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers/3.0.0

**Comment by RussKie** [comment]
Thank you, I'll give it a go.

I was half expecting "3.0.0-beta2.final-realfinal.v2" 😄

**Pull request merged**
