### PR TITLE
Add missing reference to Nuget package 

### PR DESCRIPTION
**Pull request by genlu**
- Add Microsoft.CodeAnalysis.Test.Resources.Proprietary package to DiagnosticsTestUtilities project.
- Modified NuGetRestore script to retore all packages in Analyzers.sln
- All tests passed when strong name verification is disabled for Microsoft.CodeAnalysis.Test.Resources.Proprietary.dll

@srivatsn @tmeschter

### CODE REVIEW

**Comment by tmeschter** [comment]
@genlu That project already has a reference to Microsoft.CodeAnalysis.Test.Resources.Proprietary, as well as an entry in the packages.config file.

**Comment by genlu** [comment]
@tmeschter Ah... I saw the missing reference when I did "msbuild src\Analyzer.sln" and jumped to the conclusion prematurely. Then I think the only changed needed is the NuGetRestore.ps1

**Comment by tmeschter** [comment]
@genlu Yes, we definitely need that change.

**Comment by genlu** [comment]
Close this PR, combine this small change into another PR I'm creating.

**Pull request closed without merging**
