### PR TITLE
Fix CA1850 codefix to keep trivia if it's interesting

### PR DESCRIPTION
**Pull request by wzchua**
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5683

### CODE REVIEW

**Review by buyaa-n — APPROVED** [review]
LGTM thanks!

**Comment by buyaa-n** [comment]
Closing and reopening to rerun the builds

**Comment by buyaa-n** [comment]
Oops got conflicts after your other PR merge @wzchua

**Comment by wzchua** [comment]
Fixed @buyaa-n

**Comment by buyaa-n** [comment]
Thanks for the prompt fix @wzchua

**Pull request merged**
