### PR TITLE
Changes post release of v2.6.2 analyzer packages

### PR DESCRIPTION
**Pull request by mavasani**

### CODE REVIEW

**Comment by mavasani** [comment]
I am seeing couple of issues here:

1. @tmat seems like builds are failing at signing step: `D:\j\workspace\Windows_NT_Re---c6b3d408\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.18473.8\tools\Sign.proj(60,5): error : Method not found: 'System.Collections.Immutable.ImmutableArray`1<System.Reflection.Metadata.CustomAttributeTypedArgument`1<!0>> System.Reflection.Metadata.CustomAttributeValue`1.get_FixedArguments()'.`

2. @sharwell Seems like `codecov` is broken: https://ci.dot.net/job/dotnet_roslyn-analyzers/job/master/job/Windows_NT_Debug_prtest/94/
```
12:35:11   codecov 1.0.3.0
12:35:11   Copyright (c) 2017 Larz White
12:35:11   
12:35:11   ERROR(S):
12:35:11     Option 'f, file' has no value.
```

**Comment by mavasani** [comment]
retest this please

**Comment by tmat** [comment]
Re [1] - I am aware, not sure what's going on. Looking into it.

**Comment by mavasani** [comment]
retest this please

**Pull request merged**
