### PR TITLE
Remove duplicate `PackageReference`

### PR DESCRIPTION
**Pull request by Youssef1313**
The other reference comes from

https://github.com/dotnet/roslyn-analyzers/blob/0e7f40d1709f0d7ffd316d89e452151a7365354b/src/Utilities/Compiler/Analyzer.Utilities.projitems#L145-L147

### CODE REVIEW

**Review by mavasani — APPROVED** [review]
Thanks

**Comment by Youssef1313** [comment]
@mavasani @sharwell I'm not sure about the remaining failure here.

**Comment by Youssef1313** [comment]
https://github.com/dotnet/sdk/issues/24747#issuecomment-1126298533 has some details. FYI @jmarolf

**Comment by Youssef1313** [comment]
@mavasani @sharwell @jmarolf This is green now.

**Pull request merged**
