### PR TITLE
Enable concurrent execution for CA5350/CA5351

### PR DESCRIPTION
**Pull request by bkoelman**
I don't see any shared state in this analyzer, so it looks like this is already thread-safe as-is. Am I missing something?

### CODE REVIEW

**Comment by mavasani** [comment]
@srivatsn @qinxgit @genlu I see 2 copies of DoNotUseInsecureCryptographicAlgorithmsAnalyzer in our solution - one in Desktop.Analyzers.Core and another in System.Security.Cryptography.Hashing.Algorithms.Analyzers.Core. Do you know why this is the case?

**Comment by mavasani** [comment]
@bkoelman - your change looks good to me.

**Comment by genlu** [comment]
The split was because some of the types/methods being checked only exist in Desktop framework (at least at the time of authoring those analyzers).

**Comment by mavasani** [comment]
Thanks @genlu - we probably need to refactor out lot of common code in there.

**Pull request merged**
