### PR TITLE
Remove System.DirectoryServices dependency in test utilities

### PR DESCRIPTION
**Pull request by Youssef1313**
Fixes https://github.com/dotnet/roslyn-analyzers/issues/6509

### CODE REVIEW

**Review by mavasani — APPROVED** [review]

**Comment by stephentoub** [comment]
I'm curious what DirectoryServices is used for here?

**Comment by Youssef1313** [comment]
https://github.com/dotnet/roslyn-analyzers/blob/c6352bf2e1bd214fce090829de1042000d021497/src/Test.Utilities/AdditionalMetadataReferences.cs#L24

I guess we can get rid of it and use AddPackages instead

**Comment by buyaa-n** [comment]
> I'm curious what DirectoryServices is used for here?

Used in `ReviewCodeForLdapInjectionVulnerabilities` analyzer test
https://github.com/dotnet/roslyn-analyzers/blob/5bfc7d566828589904bd9e15991a728e5488eab0/src/NetAnalyzers/UnitTests/Microsoft.NetCore.Analyzers/Security/ReviewCodeForLdapInjectionVulnerabilitiesTests.cs#L32

**Review by buyaa-n — APPROVED** [review]
LGTM

**Pull request merged**
