### PR TITLE
Fix CA1715 false negative for single-letter identifiers

### LINKED ISSUE #1604: CA1715 false negative for single letter identifiers
#### Analyzer package

Example: Microsoft.CodeQuality.Analyzers, version [2.6.0](https://www.nuget.org/packages/Microsoft.CodeQuality.Analyzers/2.6.0)

#### Analyzer

CA1715 IdentifiersShouldHaveCorrectPrefix

#### Repro steps

Create a generic method with the parameter names `K, V`:

https://github.com/dotnet/roslyn-analyzers/blob/478f95b3aeb95ae4872a475ec8f165ca9477d102/src/Test/Utilities/MarkupTestFile.cs#L173

#### Expected behavior

CA1715 is reported. The developer is expected to correct the violation by changing the generic parameters to (in this case) `TKey, TValue`.

#### Actual behavior

CA1715 is not reported. The false negative bug was introduced in response to #937.

### PR DESCRIPTION
**Pull request by sharwell**
Fixes #1604

### CODE REVIEW

**Comment by mavasani** [comment]
I recall this causing lot of violations in common repos. I vote against making this change unless there is public request.

**Comment by sharwell** [comment]
> I recall this causing lot of violations in common repos. 

Yes, I was hoping to fix them because they are deviations from the expected code style.

> I vote against making this change unless there is public request.

The analyzer is not serving its intended purpose in the current form. The two alternatives I see are:

1. Fix this
2. Fix this, and mark the analyzer disabled by default

These seem equally reasonable, especially considering the lack of a code fix for these violations.

**Comment by mavasani** [comment]
> Yes, I was hoping to fix them because they are deviations from the expected code style. The analyzer is not serving its intended purpose in the current form

I do not agree with either of these statements. Analyzers need to be sensible, not rigid about recommendations, especially when it comes to "style" or "naming". FxCop rules had large number of special cases to avoid noise for cases where common code patterns did not meet the recommended coding style. As long as the common patterns are about "style" rather then "correctness" or "performance", we *should* be flexible. I think it is extremely common to have single letter type parameter names, and then generally are pretty self explanatory from the usage, and users don't confuse them with other symbol names. When the type parameter names are longer, they tend to cause confusion with other symbol names and hence the recommendation from the rule is indeed valuable.

**Comment by sharwell** [comment]
> I think it is extremely common to have single letter type parameter names, and then generally are pretty self explanatory from the usage, and users don't confuse them with other symbol names.

**Comment by sharwell** [comment]
> I think it is extremely common to have single letter type parameter names, and then generally are pretty self explanatory from the usage, and users don't confuse them with other symbol names.

CA1715 is a naming guideline for publicly-exposed types and members, as opposed to a readability rule intended to disambiguate names. The convention you describe may be usable, but it does not adhere to our expectations for consistency among naming of public APIs. Users not intending to follow these rules, e.g. because they are not shipping a public API or their naming practices deviate from "our" .NET style, would be encouraged to disable this rule.

**Comment by mavasani** [comment]
> The convention you describe may be usable, but it does not adhere to our expectations for consistency among naming of public APIs. 

Exactly - this is the aspect of the coding guideline that I think is not at all sensible. I don't see how shipping a public type `MyDictionary<K, V>` is not acceptable, it is surely much better then `MyDicitonary<T1, T2>` or `MyDicitonary<TK, TV>`, which this guideline accepts, and is no better then `MyDicitonary<TKey, TValue>`. Given the fact that almost all of the software industry and academia accepts and uses single letter type parameter names, trying to flag these cases just makes the rule seem stupid and almost guarantees that everyone is going to turn it off.

>  Users not intending to follow these rules, e.g. because they are not shipping a public API or their naming practices deviate from "our" .NET style, would be encouraged to disable this rule (or leave it disabled if that's the default).

I think this is an extremely rigid thought and way to think about .NET coding style and is guaranteed to take more software programmers away from .NET rather then attract them. Our .NET coding style should be sensible, open to changes when required and surely not try to go against coding style and patterns followed in almost all other languages and also widely followed in all the common .NET repos, including Roslyn. Flagging lot of violations, which are not leading to any productive changes is super annoying, and this change explicitly does that. Let's fix the .NET guidelines to be sensible, and not try to fight the world!

**Comment by 333fred** [comment]
I have to agree with @mavasani for this particular issue. However, I think the argument here exposes a potential need to have more configurable analyzers. In Roslyn, for example, I can definitely see an ask for not shipping any public single-letter generic parameters, but this might not apply to many other repos.

Side note:
Our documentation on this rule currently states that this pull request is the behavior of CA1715. https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1715-identifiers-should-have-correct-prefix
> This rule reports violations for generic type parameter names such as 'V' and 'Type'.

**Comment by mavasani** [comment]
@333fred This PR indeed matches the documentation and the binary FxCop implementation. In fact the original analyzer implementation also matched it, but we loosened the analyzer for single letter type parameters for the reasons mentioned above. I recommend changing the CA1715 documentation to match the current analyzer implementation.

**Comment by sharwell** [comment]
In my experience, single-letter detection is one of, if not _the_ most valuable aspect of this analyzer. Developers proficient with Java tend to use single-letter names, e.g. [`List<E>`](https://docs.oracle.com/javase/8/docs/api/java/util/List.html), [`Map<K, V>`](https://docs.oracle.com/javase/8/docs/api/java/util/Map.html), or [`BiFunction<T, U, R>`](https://docs.oracle.com/javase/8/docs/api/java/util/function/BiFunction.html). The corresponding names for these in .NET are [`IList<T>`](https://docs.microsoft.com/dotnet/api/system.collections.generic.ilist-1), [`IDictionary<TKey, TValue>`](https://docs.microsoft.com/dotnet/api/system.collections.generic.idictionary-2), and [`Func<T1, T2, TResult>`](https://docs.microsoft.com/dotnet/api/system.func-3).

If we leave this analyzer as it is, its primary value for me historically will be completely eliminated.

**Comment by mavasani** [comment]
I think the primary difference here is in the intent of the analyzer consumer - 
1. Are they looking at the analyzer to abide by the common .NET practices and guidelines? A beginner who is open to any naming style would prefer the diagnostic/fix on single letter type parameter names.
2. Are they looking at the analyzer to tell them about _real_ issues in their code/public API surface? An experienced programmer coming from another programming language or academia would find the diagnostic/fix on single letter type parameter names extremely annoying and probably be forced to turn off the rule, missing out on useful violations in multi-letter cases.

I don't think there is a single answer to the correct analyzer behavior, and probably @333fred's suggestion of analyzer options is the only way to account for all users and preferences. I for one would always vote against analyzers being too pedantic and vote for category 2 to be the default.

Tagging @kuhlenh @jinujoseph @dotnet/roslyn-analysis for more views and probably discuss in the next design meeting.

**Comment by mavasani** [comment]
@sharwell can we close this PR in favor of https://github.com/dotnet/roslyn-analyzers/pull/2010?

**Comment by mavasani** [comment]
Closing the PR as this is now fixed with #2010

**Pull request closed without merging**
