### PR TITLE
Port Async006 unit tests from Unfactored

### PR DESCRIPTION
**Pull request by jamesqo**
Contributes towards https://github.com/dotnet/roslyn-analyzers/issues/1460; I'll wait for feedback on this PR before I port tests for the rest of the async analyzers. I didn't bother to prune the test code too much for fear of changing the validity of the tests, so you'll still see e.g. pascal case method identifiers in the strings.

/cc @333fred, @mavasani

### CODE REVIEW

**Comment by jamesqo** [comment]
@333fred I'm seeing these errors in CI, although all tests seem to be passing. Do you know what they mean?

```
XUnit : error : D:\j\workspace\windows_debug---c729d7ab\artifacts\Debug\TestResults\Microsoft.CodeQuality.Analyzers.UnitTests_net46_x64.html [net46|x64] [D:\j\workspace\windows_debug---c729d7ab\src\Microsoft.CodeQuality.Analyzers\UnitTests\Microsoft.CodeQuality.Analyzers.UnitTests.csproj]
20:27:16   Running tests: D:\j\workspace\windows_debug---c729d7ab\artifacts\Debug\bin\MetaCompilation.Analyzers.UnitTests\net46\MetaCompilation.Analyzers.UnitTests.dll [net46|x64]
20:27:17   Tests succeeded: D:\j\workspace\windows_debug---c729d7ab\artifacts\Debug\bin\MetaCompilation.Analyzers.UnitTests\net46\MetaCompilation.Analyzers.UnitTests.dll [net46|x64]
20:27:17 
20:27:17 Build FAILED.
20:27:17 
20:27:17 
XUnit : error : D:\j\workspace\windows_debug---c729d7ab\artifacts\Debug\TestResults\Microsoft.CodeQuality.Analyzers.UnitTests_net46_x64.html [net46|x64] [D:\j\workspace\windows_debug---c729d7ab\src\Microsoft.CodeQuality.Analyzers\UnitTests\Microsoft.CodeQuality.Analyzers.UnitTests.csproj]
```

**Comment by 333fred** [comment]
@jamesqo it appears that there are test failures, though I'm not sure why Jenkins isn't reporting them. @tmat, can you look at that? The test error is here:
```
Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.UnitTests.DoNotMixBlockingAndAsyncTests.NonAsyncWait [FAIL]
      Test contains compilation error(s). Pass TestValidationMode.AllowCompileErrors if these are intended:
Test0.cs(16,13): error CS0120: An object reference is required for the non-static field, method, or property 'Task.Wait()'
Test0.cs(14,14): error CS0161: 'Program.Example()': not all code paths return a value
```
https://ci.dot.net/job/dotnet_roslyn-analyzers/job/master/job/windows_debug_prtest/424/artifact/artifacts/debug/TestResults/Microsoft.CodeQuality.Analyzers.UnitTests_net46_x64.log

**Comment by jamesqo** [comment]
@333fred That's funny, it looks like the source strings I copied from Unfactored don't compile. Have the tests in there ever been run?

**Comment by jamesqo** [comment]
@333fred @mavasani PTAL, this is blocking me from porting unit tests for other analyzers (I don't want to do something incorrectly in all of the PRs, and then change all of them when you leave feedback here). All of the tests are now passing.

**Comment by mavasani** [comment]
Closing this PR as it has gone stale. Also the recommendation is now to use https://www.nuget.org/packages/Microsoft.VisualStudio.Threading for async analyzers.

**Pull request closed without merging**
