### PR TITLE
Update reference to NuGet package

### PR DESCRIPTION
**Pull request by genlu**
Fix test failure caused by improperly signed Microsoft.CodeAnalysis.Test.Resources.Proprietary.dll
on machine not skipping SN verification.

@tmeschter @srivatsn

### CODE REVIEW

**Comment by tmeschter** [comment]
:+1:

**Comment by tmeschter** [comment]
@genlu You can merge this in. If you don't have permission to merge it in, let me know and we'll get that worked out.

**Comment by genlu** [comment]
@tmeschter I don't have write permission, could you please add me as a contributor?

**Comment by tmeschter** [comment]
@genlu I think we need to get you added to the "dotnet" organization. I'll look into that and send you an email.

**Pull request merged**
