### PR TITLE
Support for Spanish translations - CodeAnalysisDiagnosticsResources.es.xlf

### PR DESCRIPTION
**Pull request by Escoto**
Some help with Spanish translations on CodeAnalysisDiagnosticsResources.es.xlf

-Build.cmd -> Successful
-Test.cmd -> Successful
-Pack -> Successful

### CODE REVIEW

**Comment by Escoto** [comment]
I checked the error. I have the most updated changes from master, and can't reproduce the issue on my local. 

Suggestion is to run ' msbuild /t:UpdateXlf ', I did using the developer console for this project only and got the following.

Build started 12/8/2020 2:16:55 PM.
Project "C:\Repos\roslyn-analyzers\src\Microsoft.CodeAnalysis.Analyzers\Core\Microsoft.CodeAnalysis.Analyzers.csproj" on node 1 (UpdateXlf target(s)).
_UpdateXlf:
Skipping target "_UpdateXlf" because all output files are up-to-date with respect to the input files.
Done Building Project "C:\Repos\roslyn-analyzers\src\Microsoft.CodeAnalysis.Analyzers\Core\Microsoft.CodeAnalysis.Analyzers.csproj" (UpdateXlf target(s)).


Build succeeded.
    0 Warning(s)
    0 Error(s)

**Comment by Evangelink** [comment]
@Escoto Please try to run `msbuild RoslynAnalyzers.sln /t:pack` it should be ok.

**Comment by Escoto** [comment]
Yes, if i run it from the developer console I get  0 warnings/0 errors. 
If I do it from PS i get an error but unrelated to the one on the pipeline, "error MSB4057: The target "pack" does not exist in the project. [C:\Repos\roslyn-analyzers\RoslynAnalyzers.sln]"

**Comment by Evangelink** [comment]
@buyaa-n What's the process for accepting user input on translations?

**Comment by buyaa-n** [comment]
@Evangelink I don't know, tagging localization team @cristianosuzuki77

**Comment by Evangelink** [comment]
We have had 2 PR from users recently so it'd be nice to decide if we accept them or not. If not let's update the readme/contribution to make it explicit. If we do let's decide on the process.

**Comment by mavasani** [comment]
@cristianosuzuki77 To help with deciding if we are fine with taking loc translation contributions from community,

**Comment by cristianosuzuki77** [comment]
For community input on translations, the process is as follow:
a. Please open a ticket agains me with the current translation and the expected/suggested translation.
b. I'll follow with the request through the translators and get a review of the translation. 
c. Once the suggestion is accepted, it will be applied on the loc system side (for future reuse) and a new PR would be made here.
d. If there is a conflict with the suggestion, it will not be accepted. This could be for several reasons, which will be then explained in the original ticket.

Please refrain from adding the suggestion directly to the files, as it will be overwritten in future PRs from loc system if the suggestion was not accepted.

**Pull request closed without merging**
