### PR TITLE
Implement DFA rule (CA1508: AvoidDeadConditionalCode)

### PR DESCRIPTION
**Pull request by mavasani**
This rule flags conditional expressions which are always true/false and null checks for operations that are always null/non-null based on predicate analysis.

This PR is based upon https://github.com/dotnet/roslyn-analyzers/pull/1635, which adds predicate analysis that enables us to implement this simple rule utilizing its results. The only relevant commit for this PR on top of #1635 is https://github.com/dotnet/roslyn-analyzers/commit/746645e06051121c4fd492803c46d052f375c88a. I will rebase this PR once #1635 is merged.

### CODE REVIEW

**Comment by heejaechang** [comment]
@sharwell the code coverage thing is awesome!

**Comment by mavasani** [comment]
@dotnet/roslyn-analysis I have rebased the PR and now it is ready for review.

**Comment by mavasani** [comment]
Ping, can I get some reviews on this one? Thanks.

**Comment by jinujoseph** [comment]
Approved to unblock testing, @333fred , @ivanbasov  to review

**Pull request merged**
