### PR TITLE
Delete unused resources

### PR DESCRIPTION
**Pull request by Youssef1313**
@Evangelink @sharwell This will probably make the other PR shorter and easier to review.

### CODE REVIEW

**Comment by drewnoakes** [comment]
Did you find these manually? I wonder if there's an opportunity to detect unused resources with an analyzer.

I suspect unused resources are quite common. I made a similar pass in the project system a while ago and reduced our binary size by a noticeable amount.

**Comment by Evangelink** [comment]
It seems rather easy to add this analyzer. We have already implemented something to read resources so we could simply look if the resource is used.

@mavasani shall we still merge this as-is or close the PR and wait for the analyzer?

**Comment by Youssef1313** [comment]
> Did you find these manually? I wonder if there's an opportunity to detect unused resources with an analyzer.
> 
> I suspect unused resources are quite common. I made a similar pass in the project system a while ago and reduced our binary size by a noticeable amount.

Found these by looking at the generated file and finding resources where CodeLens says: "0 references".

**Comment by mavasani** [comment]
> It seems rather easy to add this analyzer. We have already implemented something to read resources so we could simply look if the resource is used.

Agreed. It would be possible to write an analyzer for detecting unused resources, but we cannot add a code fix here as it needs full project analysis and also the lightbulb needs to be in resx file, we do not support code fixes in non-source files yet. +1 to add this analyzer though.

**Comment by mavasani** [comment]
> @mavasani shall we still merge this as-is or close the PR and wait for the analyzer?

@Evangelink Seems fine to go either route. If you or @Youssef1313 are keen on implementing the analyzer, then keeping these unused resources in our repo to test out the new analyzer also seems fine. I'll let you both make a call on this.

**Comment by Youssef1313** [comment]
> > @mavasani shall we still merge this as-is or close the PR and wait for the analyzer?
> 
> @Evangelink Seems fine to go either route. If you or @Youssef1313 are keen on implementing the analyzer, then keeping these unused resources in our repo to test out the new analyzer also seems fine. I'll let you both make a call on this.

I was only deleting unused resources when I find that "Title" and "Message" and "Description" are all unused.

But there are still unused resources, for example `MarkAssembliesWithComVisibleMessageNoAttribute` that belongs to <https://github.com/dotnet/roslyn-analyzers/blob/f167914d442d0ae0055b28a1c92e5b9d446fdbdb/src/NetAnalyzers/Core/Microsoft.CodeQuality.Analyzers/ApiDesignGuidelines/MarkAssembliesWithComVisible.cs>, which may not be needed to be deleted, but instead it should be used there.

So there is still room to test the analyzer when written.

Also note that there are other resource files that I didn't touch which can have unused resources as well.

**Comment by mavasani** [comment]
@Youssef1313 Sounds good to me. Can you please resolve merge conflicts?

**Review by mavasani — APPROVED** [review]

**Review by Evangelink — APPROVED** [review]

**Comment by drewnoakes** [comment]
I filed https://github.com/dotnet/roslyn-analyzers/issues/4865 to track the idea of having an analyzer detect unused resources.

**Comment by Evangelink** [comment]
Ping @mavasani

**Review by mavasani — APPROVED** [review]

**Pull request merged**
