### PR TITLE
Test PR for #6367

### PR DESCRIPTION
**Pull request by mavasani**
Test PR for #6367

### CODE REVIEW

**Comment by mavasani** [comment]
@Youssef1313

**Comment by Youssef1313** [comment]
@mavasani This is green :(

**Comment by mavasani** [comment]
Yes, will investigate why the analyzers are not executing

**Comment by mavasani** [comment]
@Youssef1313 The problem seems to be that we enable CAxxxx rules as warnings with the below: https://github.com/dotnet/roslyn-analyzers/blob/2b5a3b2f8e5e841c18cde4855a22cf8161ad4986/src/Directory.Build.props#L29-L32

Due to this regression: https://github.com/dotnet/roslyn-analyzers/issues/6245, CAxxxx rules are no longer being bulk escalated to warning/error. I am going to work on a PR to pull in the latest NetAnalyzers package in the repo to first fix this and also the new violations that come out of it. I am going to block your PR https://github.com/dotnet/roslyn-analyzers/pull/6367 until this work is done.

**Comment by mavasani** [comment]
@Youssef1313 This also explains why https://github.com/dotnet/roslyn-analyzers/pull/6339 had no new violations.

**Comment by mavasani** [comment]
> @Youssef1313 This also explains why #6339 had no new violations.

Moving to latest pre-release NetAnalyzers package produces 410 CA warnings!!

**Comment by mavasani** [comment]
CLosin

**Pull request closed without merging**
