### PR TITLE
Do not fire 'make member static' when a method references a primary constructor parameter.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**
Fixes https://github.com/dotnet/roslyn-analyzers/issues/6573

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
@sharwell @mavasani ptal.

**Comment by CyrusNajmabadi** [comment]
@mavasani @sharwell , updating to the new roslyn is producing errors like:

```
Code fix is attempting to provide a fix for a non-local analyzer diagnostic
Expected: False
Actual:   True
```

It looks like we need to update analyzers here to follow the new rules you set out that diagnostics can only be reported within the span of hte entity we're getting a a callback for.

**Comment by mavasani** [comment]
> @mavasani @sharwell , updating to the new roslyn is producing errors like:
> 
> ```
> Code fix is attempting to provide a fix for a non-local analyzer diagnostic
> Expected: False
> Actual:   True
> ```
> 
> It looks like we need to update analyzers here to follow the new rules you set out that diagnostics can only be reported within the span of hte entity we're getting a a callback for.

Yes, this is a pending work item, see https://github.com/dotnet/roslyn-analyzers/pull/6560#discussion_r1172789018. However, I don't know if any of the existing tests for this analyzer failed with this issue - @sharwell might know more.

You can disable the non-local diagnostic check with `CodeFixTestBehaviors = CodeFixTestBehaviors.SkipLocalDiagnosticCheck` just like in the comment above. Fix for #6598 should remove all the usages of `CodeFixTestBehaviors.SkipLocalDiagnosticCheck`

**Review by mavasani — APPROVED** [review]

**Comment by mavasani** [comment]
Tagging @buyaa-n

@CyrusNajmabadi - do we need to backport this fix to .NET 7 servicing branch? I am not sure if primary constructors are available with compiler shipping in .NET 7 SDK.

**Comment by CyrusNajmabadi** [comment]
Just to be clear.  The "non-local" errors are from *other* tests.  You would still like me to dsiable them?

**Comment by CyrusNajmabadi** [comment]
Importantly, it looks like there are several hundred tests in this category:

**Comment by mavasani** [comment]
> Importantly, it looks like there are several hundred tests in this category:
> 
> image

Oh that is a huge number. Probably coming from further updates to non-local diagnostics semantics. If your PR is okay to wait till early next week, I can work on this today/tomorrow/over the weekend. If not, feel free to disable non-local diagnostics tests for all the failures and merge your PR, I'll try to get to them as soon as possible.

**Comment by CyrusNajmabadi** [comment]
Sounds good.

**Comment by CyrusNajmabadi** [comment]
@mavasani can you help update dotnet/roslyn to use this new version of roslyn-analyzers?  Thanks!

**Pull request merged**
