### PR TITLE
Fix #7008 Make AnalyzerOptionsExtensions to have public modifier instead of internal

### LINKED ISSUE #7008: Make `AnalyzerOptionsExtensions` public
Hi there,

I am trying to provide some options to my own analyzers. The extensions in [`AnalyzerOptionsExtensions`](https://github.com/dotnet/roslyn-analyzers/blob/main/src/Utilities/Compiler/Options/AnalyzerOptionsExtensions.cs) provide everthing one could possibly need to implement this, even caching is implemented. Sadly those extensions are internal and I cannot use them.

Can you make this public? If not, why? Otherwise I basically need to copy the file to have a solid foundation for options handling.

So lonG

Daniel

### PR DESCRIPTION
**Pull request by eriawan**
Fixes #7008 

Make AnalyzerOptionsExtensions to have public modifier instead of internal

### CODE REVIEW

**Comment by eriawan** [comment]
@mavasani 

After I compiled on my local, I got some errors that says some objects need to be modified to be public:

```
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(39,45): error CS0050: Inconsistent accessibility: return type 'SymbolVisibilityGroup' is less accessible than method 'AnalyzerOptionsExtensions
.GetSymbolVisibilityGroupOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation, SymbolVisibilityGroup)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensitiveAna
lyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(39,45): error CS0051: Inconsistent accessibility: parameter type 'SymbolVisibilityGroup' is less accessible than method 'AnalyzerOptionsExtensi
ons.GetSymbolVisibilityGroupOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation, SymbolVisibilityGroup)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensitive
Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(75,47): error CS0050: Inconsistent accessibility: return type 'EnumValuesPrefixTrigger' is less accessible than method 'AnalyzerOptionsExtensio
ns.GetEnumValuesPrefixTriggerOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation, EnumValuesPrefixTrigger)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensit
iveAnalyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(75,47): error CS0051: Inconsistent accessibility: parameter type 'EnumValuesPrefixTrigger' is less accessible than method 'AnalyzerOptionsExten
sions.GetEnumValuesPrefixTriggerOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation, EnumValuesPrefixTrigger)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSen
sitiveAnalyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(231,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetNullCheckValidationMethodsOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensitiveAnalyz
ers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(238,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetAdditionalStringFormattingMethodsOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensitiv
eAnalyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(308,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetDisallowedSymbolNamesWithValueOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensitiveAnaly
zers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(322,59): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<string?>' is less accessible than method 'AnalyzerOp
tionsExtensions.GetAdditionalRequiredSuffixesOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensitiveAnalyz
ers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(371,69): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<INamedTypeSymbol?>' is less accessible than method '
AnalyzerOptionsExtensions.GetAdditionalRequiredGenericInterfaces(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSe
nsitiveAnalyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(417,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetInheritanceExcludedSymbolNamesOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation, string)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSen
sitiveAnalyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(425,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetAdditionalUseResultsMethodsOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensitiveAnaly
zers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(432,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetEnumerationMethodsOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.cspr
oj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(439,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetLinqChainMethodsOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.csproj
]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(569,28): error CS0051: Inconsistent accessibility: parameter type 'SymbolVisibilityGroup' is less accessible than method 'AnalyzerOptionsExtens
ions.MatchesConfiguredVisibility(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation, SymbolVisibilityGroup)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensitiveAn
alyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(603,28): error CS0051: Inconsistent accessibility: parameter type 'SymbolModifiers' is less accessible than method 'AnalyzerOptionsExtensions.M
atchesConfiguredModifiers(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation, SymbolModifiers)' [\roslyn-analyzers\src\PerformanceSensitiveAnalyzers\Core\Microsoft.CodeAnalysis.PerformanceSensitiveAnalyzers.cspro
j]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(39,45): error CS0050: Inconsistent accessibility: return type 'SymbolVisibilityGroup' is less accessible than method 'AnalyzerOptionsExtensions
.GetSymbolVisibilityGroupOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation, SymbolVisibilityGroup)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(39,45): error CS0051: Inconsistent accessibility: parameter type 'SymbolVisibilityGroup' is less accessible than method 'AnalyzerOptionsExtensi
ons.GetSymbolVisibilityGroupOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation, SymbolVisibilityGroup)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(75,47): error CS0050: Inconsistent accessibility: return type 'EnumValuesPrefixTrigger' is less accessible than method 'AnalyzerOptionsExtensio
ns.GetEnumValuesPrefixTriggerOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation, EnumValuesPrefixTrigger)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(75,47): error CS0051: Inconsistent accessibility: parameter type 'EnumValuesPrefixTrigger' is less accessible than method 'AnalyzerOptionsExten
sions.GetEnumValuesPrefixTriggerOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation, EnumValuesPrefixTrigger)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(231,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetNullCheckValidationMethodsOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(238,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetAdditionalStringFormattingMethodsOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(308,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetDisallowedSymbolNamesWithValueOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(322,59): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<string?>' is less accessible than method 'AnalyzerOp
tionsExtensions.GetAdditionalRequiredSuffixesOption(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(371,69): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<INamedTypeSymbol?>' is less accessible than method '
AnalyzerOptionsExtensions.GetAdditionalRequiredGenericInterfaces(AnalyzerOptions, DiagnosticDescriptor, ISymbol, Compilation)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(417,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetInheritanceExcludedSymbolNamesOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation, string)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(425,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetAdditionalUseResultsMethodsOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(432,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetEnumerationMethodsOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
\roslyn-analyzers\src\Utilities\Compiler\Options\AnalyzerOptionsExtensions.cs(439,56): error CS0050: Inconsistent accessibility: return type 'SymbolNamesWithValueOption<Unit>' is less accessible than method 'AnalyzerOptio
nsExtensions.GetLinqChainMethodsOption(AnalyzerOptions, DiagnosticDescriptor, SyntaxTree, Compilation)' [\roslyn-analyzers\src\Roslyn.Diagnostics.Analyzers\Core\Roslyn.Diagnostics.Analyzers.csproj]
```
Should I make `SymbolVisibilityGroup`, `EnumValuesPrefixTrigger` `SymbolNamesWithValueOption<TValue>` and the remaining impacted class/enums such as `SymbolModifiers` as public too?

**Comment by mavasani** [comment]
> Should I make SymbolVisibilityGroup, EnumValuesPrefixTrigger SymbolNamesWithValueOption<TValue> and the remaining impacted class/enums such as SymbolModifiers as public too?

That sounds reasonable to me.

**Comment by eriawan** [comment]
Done setting classes to public.

@mavasani do I have to update the `PublicAPI.Unshipped.txt` as well?

**Comment by mavasani** [comment]
> Done setting classes to public.
> 
> @mavasani do I have to update the `PublicAPI.Unshipped.txt` as well?

Yes, please use the code fix to add the entries to `PublicAPI.Unshipped.txt`

**Comment by eriawan** [comment]
Done committing updated PublicAPI.Unshipped.txt file.
Ok, there's a merge conflict, I'm going to resolve this first.

**Comment by eriawan** [comment]
@mavasani 
Hang on, it seems there are compilation errors after resolving merge conflict, These errors are caused by conflicting names of class in the Microsoft.CodeAnalysis.NetAnalyzers and Test.Utilities.

For example: (as shown in the Azure Pipelines https://dev.azure.com/dnceng-public/public/_build/results?buildId=513774&view=logs&j=f0f0520d-467b-5d1d-a95d-4e3a2581fe8a&t=c140c00f-6c0a-5356-d099-4e047a5525ed&l=163)
```
D:\a\_work\1\s\src\Utilities.UnitTests\Options\SymbolNamesWithValueOptionTests.cs(22,54): error CS0433: The type 'Unit' exists in both 'Microsoft.CodeAnalysis.NetAnalyzers, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Test.Utilities, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35' [D:\a\_work\1\s\src\Utilities.UnitTests\Analyzer.Utilities.UnitTests.csproj]
```

Ok, I'm going to try to resolve this error, I'll update you again when it's done.

**Comment by eriawan** [comment]
@mavasani 

I need some help on how to resolve the compile error on this project of Analyzer.Utilities.Unittests project, because the class name and the namespace on both Microsoft.CodeAnalysis.NetAnalyzers and Test.Utilities references are exactly the same, because they are actually pointing to the same source file.

Is there any guidance I should do to fix this errors?

**Comment by eriawan** [comment]
@mavasani 

Pardon, please review and let me know how to proceed further, as I'm currently having the problem of errors in https://github.com/dotnet/roslyn-analyzers/pull/7085#issuecomment-1875964064 

Thanks in advance!

**Comment by eriawan** [comment]
@mavasani 

Just to remind, could you help me to solve the compile problem I've described in https://github.com/dotnet/roslyn-analyzers/pull/7085#issuecomment-1875964064 ?

Or should I update the Test.Utilities.csproj to remove the line of Import Project Analyzer.Utilities.projitems and add project reference to Microsoft.CodeAnalysis.NetAnalyzers instead?

Please confirm.

**Comment by mavasani** [comment]
@eriawan We need these types to be public only when included in the `AnalyzerUtilities` project. One way to work around this issue is to define them in source with preprocessor directives:

```c#
#if ANALYZER_UTILITIES
public class Unit
#else
internal class Unit
#end if
```

And define the preprocessor directive `ANALYZER_UTILITIES` in `AnalyzerUtilities.csproj`

**Comment by eriawan** [comment]
> @eriawan We need these types to be public only when included in the `AnalyzerUtilities` project. One way to work around this issue is to define them in source with preprocessor directives:
> 
> ```cs
> #if ANALYZER_UTILITIES
> public class Unit
> #else
> internal class Unit
> #endif
> {
>    ... class definition
> }
> ```
> 
> And define the preprocessor directive `ANALYZER_UTILITIES` in `AnalyzerUtilities.csproj`

@mavasani 
Thanks for the suggestion! Sorry for late reply.

I'm going to do this today 🙂

**Comment by eriawan** [comment]
@mavasani 

Done updating TestUtilities.csproj to add constant/symbol and also update some classes to have`#if` symbols to separate `public` and `internal` modifiers.
Looking at the CI of the build, all is green 🟢 ✔️ 

Please review, thanks in advance!

**Review by mavasani — APPROVED** [review]
Thanks!

**Pull request merged**
