### PR TITLE
Add CollectionExpression support to CA1870 (UseSearchValues)

### PR DESCRIPTION
**Pull request by MihaZupan**
Followup after #6898 to add recognition for collection expression patterns as well.

Currently, if you write something like
```c#
private static readonly char[] s_chars = new[] { 'a', 'e', 'i', 'o', 'u', 'A' };
public static int Test(ReadOnlySpan<char> s) => s.IndexOfAny(s_chars);
```

you will be offered two fixers: one to replace `s_chars` with `SearchValues.Create("aeiouA")`, and the other to replace the array creation with `['a', 'e', 'i', 'o', 'u', 'A']`.
If you accept the latter, you won't be offered the `SearchValues` fixer anymore since we don't recognize the pattern.

This PR adds recognition for patterns like
```c#
static readonly char[] s_chars = ['a', 'e', 'i', 'o', 'u', 'A'];

text.IndexOfAny(['a', 'e', 'i', 'o', 'u', 'A']);
text.IndexOfAny([(byte)'a', (byte)'e', (byte)'i', (byte)'o', (byte)'u', (byte)'A']);
text.IndexOfAny(s_chars);
```

### CODE REVIEW

**Comment by MihaZupan** [comment]
cc: @stephentoub

**Comment by MihaZupan** [comment]
@dotnet/roslyn-analysis who would be the right person to review this one?

**Review by buyaa-n — APPROVED** [review]
LGTM, I will let @CyrusNajmabadi take another look

**Review by CyrusNajmabadi — COMMENTED** [review]
Looks reasonable to me :-)

**Pull request merged**
