### PR TITLE
Disable few rules that do not have a code fix from analyzer VSIX

### PR DESCRIPTION
**Pull request by mavasani**

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @jinujoseph @heejaechang @jinujoseph @kuhlenh

**Comment by mavasani** [comment]
@tmat seems like unit tests are not running in Jenkins for dev15.3 branch.

**Comment by tmat** [comment]
test ci please

**Comment by tmat** [comment]
test this please

**Comment by tmat** [comment]
@mavasani fixing...

**Comment by tmat** [comment]
test ci please

**Comment by tmat** [comment]
test ci please

**Comment by tmat** [comment]
test this please

**Comment by heejaechang** [comment]
👍

**Comment by mavasani** [comment]
@tmat - tests are now running. Thanks!

**Pull request merged**
