### PR TITLE
Fix couple of NREs in newly added rules

### PR DESCRIPTION
**Pull request by mavasani**
1. Fix NRE in ReviewSQLQueriesForSecurityVulnerabilities while computing well known types.
2. Fix NRE in PointsToDataFlowOperationVisitor for null type for an IMethodReferenceOperation

### CODE REVIEW

**Comment by mavasani** [comment]
@jinujoseph - after applying the fixes in this PR, I was able to successfully build Roslyn.sln with debug bits of the experimental package. It produces 300+ warnings for Dispose rules and I have already identified 3 primary categories for these violations:
1. False negatives - cases where we should not be reporting the diagnostics, I will try to create minimal repros for these and investigate.
2. True violations: There are actually quite a few places where we are leaking disposable objects in normal control flow paths. I will work on sending a PR with these fixes.
3. Dispose ownership patterns: For quite a few cases a disposable object is created in a method and passed to constructor of another disposable type, which takes over its ownership and also disposes the passed object. This pattern is not as per the FxCop and our implementation, so we either need to make the dispose rules smarter to understand such patterns OR implement https://github.com/dotnet/roslyn-analyzers/issues/1587 to allow end users to configure dispose ownership via additional files. I personally prefer starting with the former, and will try to prototype it - we can switch to later if we still see lot of cases that we cannot detect.

**Comment by mavasani** [comment]
Example of true violations: We are not disposing `StringWriter` objects in [SyntaxNode.GetText](http://source.roslyn.io/#Microsoft.CodeAnalysis/Syntax/SyntaxNode.cs,326) and [GreenNode.ToString](http://source.roslyn.io/#Microsoft.CodeAnalysis/Syntax/GreenNode.cs,630)

**Comment by sharwell** [comment]
>  We are not disposing `StringWriter` objects in ...

:memo: `StringWriter.Dispose()` is a NOP (the containing doesn't have a user-defined finalizer, so even the `GC.SuppressFinalize` call is a NOP).

**Comment by mavasani** [comment]
> `StringWriter.Dispose()` is a NOP

Actually that is not true. [StringWriter.Dispose](https://referencesource.microsoft.com/#mscorlib/system/io/stringwriter.cs,47872c8709d73365) does set a flag preventing further usage of the writer to throw exceptions. Additionally, I believe this is an internal implementation detail, which the user should not rely upon. I think it is a better practice to always dispose disposable objects if you have the dispose ownership, and not rely on any implementation details of the underlying Dispose method.

**Pull request merged**
