### PR TITLE
Use special source generator suffix when generating code.

### PR DESCRIPTION
**Pull request by AraHaan**
Fixes https://github.com/dotnet/roslyn-analyzers/issues/5958.

### CODE REVIEW

**Comment by AraHaan** [comment]
Failure might be from using the msbuild collector for coverlet:

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md

**Comment by AraHaan** [comment]
The failure is a known coverlet.msbuild issue.

**Review by Youssef1313 — APPROVED** [review]
LGTM, but whatever tool that respects `.g.cs` should also respect the `// <auto-generated/>` comment at the beginning of source files.

**Comment by AraHaan** [comment]
Unfortunately there are multiple different ways of also marking a file with that comment (or rather multiple different versions of the comment that it would need to check for making the check complex).

**Review by sharwell — CHANGES_REQUESTED** [review]
**.Designer.cs** is already one of the special generated source suffixes. I don't believe there is any need to change from **.Designer.cs** to **.g.cs**.

**Pull request closed without merging**
