### PR TITLE
Add long paths prerequisite to NetCore_GettingStarted.md

### PR DESCRIPTION
**Pull request by carlossanlop**
Improve documentation to prevent contributors from falling into this issue: https://github.com/dotnet/roslyn-analyzers/issues/6632#issuecomment-1564818030

### CODE REVIEW

**Comment by buyaa-n** [comment]
This is related to any build right? Maybe add into https://github.com/dotnet/roslyn-analyzers#getting-started?

**Comment by carlossanlop** [comment]
> This is related to any build right? Maybe add into https://github.com/dotnet/roslyn-analyzers#getting-started?

Ah, good point. I missed those instructions.

I think it's worth having this info in both places, if that's alright with you.

**Review by sharwell — CHANGES_REQUESTED** [review]
We should wait for https://github.com/dotnet/roslyn/pull/68217 to merge and adopt the same strategy here.

**Comment by carlossanlop** [comment]
@sharwell should that roslyn PR block this docs PR though? Can you please explain?

**Comment by sharwell** [comment]
@carlossanlop I believe yes. Once the strategy from dotnet/roslyn is finalized, the documentation will be redundant because the build will perform the necessary change so the user doesn't need to. Also, the steps to enable the feature will be simplified to running a script which the error output points to.

**Pull request closed without merging**
