### PR TITLE
Bump up the version numbers of analyzer packages to 1.1.0

### PR DESCRIPTION
**Pull request by mavasani**

### CODE REVIEW

**Comment by mavasani** [comment]
@srivatsn @tmeschter

**Comment by tmeschter** [comment]
LGTM. This is a good opportunity to document the versioning scheme we want to use, and why we're deviating from it for the time being. I'd suggest putting that into the commit message at a minimum, but the top-level README.md (or another file linked to from the top-level README.md) would be a better place.

**Comment by srivatsn** [comment]
:+1:  +1 to the documentation suggestion.

**Comment by mavasani** [comment]
Thanks, added the documentation.

**Pull request merged**
