### PR TITLE
Update perf test baseline following SDK version change

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Review by jmarolf — APPROVED** [review]

**Comment by mavasani** [comment]
@sharwell @jmarolf Anything more to be done here? We have the perf leg failing on all our PRs for quite a while now.

**Comment by sharwell** [comment]
@mavasani I don't know how to fix it. The same test fails in this pull request.

**Comment by jmarolf** [comment]
@sharwell I believe this was addressed in a different PR

**Pull request closed without merging**
