### PR TITLE
Fix CA1508 bugs

### LINKED ISSUE #4327: CA1508 false positive in IAsyncEnumerable.ConfigureAwait
### Analyzer

**Diagnostic ID**: [CA1508](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 5 SDK or later](https://docs.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 5.0.100-rc2](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

CA1508 fired on implicit lowered code of `await foreach`.

### Steps To Reproduce

Using `<AnalysisMode>AllEnabledByDefault</AnalysisMode>`:

```csharp
        static async IAsyncEnumerable<int> M(IAsyncEnumerable<int> iae)
        {
            await foreach (int i in iae.ConfigureAwait(false)) // here
            {
                if (i > 0)
                    yield return i;
            }
        }
```

### Expected behavior

Not fired. The comparison with null might come from defensive pattern in compiler lowered code for `await foreach`.

### Actual behavior

Warning CA1508: `iae.ConfigureAwait(false)` can never be `null`.

### LINKED ISSUE #4382: CA1508 should not occur in a using statement's expression
### Analyzer

**Diagnostic ID**: [CA1508](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.1 (Latest)

### Describe the bug
I don't expect CA1508 on using statement's expression.

### Steps To Reproduce
```cs
using System;

class C
{
    void F(IDisposable x)
    {
        if (x != null)
        {
            using (x) { } // CA1508 occurs here
        }
    }

    static void Main() { }
}
```

### Expected behavior
I know that  [a using statement expands to a code containing null checking](https://stackoverflow.com/questions/278902/using-statement-vs-try-finally/278924#278924), but I use a using statement for disposing object. So I don't expect CA1508 on using statement's expression.

### Actual behavior
CA1508 occurs: `'x' is never 'null'. Remove or refactor the condition(s) to avoid dead code.`

## Additional context
Note 1. A variable used for a conditional branch and a variable used for a using statement are irrelevant:
```cs
using System;
using System.IO;

class C
{
    void F(IDisposable x)
    {
        if (x != null)
        {
            using (new MemoryStream()) { } // CA1508 occurs here
        }
    }

    static void Main() { }
}
```

Note 2. If I omit the null checking then CA1508 does not occur in a using statement:
```cs
using System;
using System.IO;

class C
{
    void F(IDisposable x)
    {
        using (new MemoryStream()) { } // CA1508 does NOT occur here
    }

    static void Main() { }
}
```

Note 3. If I use a using statement for `local_variable_declaration` then CA1508 does not occur even if a null checking exists:
```cs
using System;
using System.IO;

class C
{
    void F(IDisposable x)
    {
        if (x != null)
        {
            using (var y = new MemoryStream()) { } // CA1508 does NOT occur here
        }
    }

    static void Main() { }
}
```

### LINKED ISSUE #4383: CA1508: False Positive in 3.3.1. Older Version 3.3.0 is working.
### Analyzer

**Diagnostic ID**: [CA1508](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.1 (Latest)

### Describe the bug / Steps To Reproduce

The following code produces two warnings:

```
public static ReadOnlyDictionary<TKey, ReadOnlyCollection<TValue>> AsReadOnlyItems<TKey, TValue>(this IDictionary<TKey, IList<TValue>> self, IEqualityComparer<TKey> keyComparer = null)
{
    _ = self ?? throw new ArgumentNullException(nameof(self));

    keyComparer ??= (self as Dictionary<TKey, TValue>)?.Comparer;
    var copy = new Dictionary<TKey, ReadOnlyCollection<TValue>>(self.Count, keyComparer);
    foreach (var kvp in self)
    {
        if (kvp.Value is null)
        {
            copy.Add(kvp.Key, null);
            continue;
        }

        var readOnlyValue = kvp.Value as ReadOnlyCollection<TValue> ?? new ReadOnlyCollection<TValue>(kvp.Value);
        copy.Add(kvp.Key, readOnlyValue);
    }

    return new ReadOnlyDictionary<TKey, ReadOnlyCollection<TValue>>(copy);
}
```

There is one warning in line ``keyComparer ??= (self as Dictionary<TKey, TValue>)?.Comparer;`` that told me that ``self`` is never null.
The other warning is in line ``var readOnlyValue = kvp.Value as ReadOnlyCollection<TValue> ?? new ReadOnlyCollection<TValue>(kvp.Value);`` where ``kvp.Value`` is meant to be never null.

### Expected behavior

The warnings should not appear.

**The specified code is working in version 3.3.0 without any changes.**

### Actual behavior

A warning for CA1508 appears.

### LINKED ISSUE #4387: CA1508 False positive with char equality
### Analyzer

**Diagnostic ID**: [CA1508](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.1 (Latest)

### Steps To Reproduce

````csharp
        private static bool TryParseUnit(string unit)
        {
            char last = unit[^1];
            if (last != 'b') // warning CA1508: 'last != 'b'' is always 'true'. Remove or refactor the condition(s) to avoid dead code.
                return false;

            return true;
        }
````

### Expected behavior

No diagnostic as the condition is not a constant.

### Actual behavior

Report a diagnostic

### Additional data

No diagnostic is reported if I inline the variable

````
if (unit[^1] != 'b') // no diagnostic
````

### LINKED ISSUE #4411: CA1508 should not warn on as expression
```cs
class A
{
    void M(object o)
    {
        if (o is A a)
        {
        //  ↓↓↓↓↓ CA1508
            (a as B)?.ToString();
        }
    }
}

class B : A
{
}
```

image

### LINKED ISSUE #4415: CA1508 False positive on Nullable DateTime
### Analyzer

**Diagnostic ID**: [CA1508](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1508): `Avoid dead conditional code`

### Analyzer source

**NuGet Package**: [Microsoft.CodeAnalysis.FxCopAnalyzers](https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers)

**Version**: v3.3.1 (Latest)

### Describe the bug

It's reporting a false positive checking that `DateTime? != null`:

```
var punchIn = (DateTime?)t.GetProperty($"SchedulePunchIn{i}Time").GetValue(dbSchedule);
var punchOut = (DateTime?)t.GetProperty($"SchedulePunchOut{i}Time").GetValue(dbSchedule);

if (punchIn != null || punchOut != null) // this line here
```

### Steps To Reproduce

Simply write the following code:
```
var a = (DateTime?)DateTime.UtcNow;
if (a != null) { }
```

### Expected behavior

It shouldn't cause a warning.

### Actual behavior

It causes a warning.

## Additional context

N/A

### PR DESCRIPTION
**Pull request by mavasani**
Recommend reviewing with whitespaces removed: https://github.com/dotnet/roslyn-analyzers/pull/4358/files?diff=unified&w=1

Fixes #4327
Fixes #4382
Fixes #4383
Fixes #4411
Fixes #4415
Fixes #4387

### CODE REVIEW

**Comment by mavasani** [comment]
@dotpaul @genlu @Evangelink Can one you please review? This PR fixes a bunch of CA1508 and DFA bugs. @dotpaul I plan to port the product changes to 2.9.x as a follow-up PR - not all tests added here are writable in that branch.

**Review by Evangelink — APPROVED** [review]
LGTM. When I see how "simple" the changes are I really should spend more time trying to understand how it works and how to debug properly.

**Comment by mavasani** [comment]
Thank you @Evangelink! 

> I really should spend more time trying to understand how it works

This is all on me not being able to dedicate some time to write up something or have a chat with you on this space. Let me try to allocate some time next week - I'll ping you on gitter.

**Comment by brian-reichle** [comment]
Will this fix also cover the following false-positive?

```csharp
static bool Foo(object value) => value is string strValue && string.IsNullOrEmpty(strValue);
//                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// Warning	CA1508	'string.IsNullOrEmpty(strValue)' is always 'false'. Remove or refactor the condition(s) to avoid dead code.
```
Whilst it's true that `strValue` won't be null, it may still be empty.

**Comment by Evangelink** [comment]
@brian-reichle I would say this is handled, look at [this test](https://github.com/dotnet/roslyn-analyzers/blob/master/src/NetAnalyzers/UnitTests/Microsoft.CodeQuality.Analyzers/Maintainability/AvoidDeadConditionalCode_NullAnalysis.cs#L6887-L6914)

**Pull request merged**
