### PR TITLE
Package the experimental analyzers along with the FxCopAnalyzers and …

### PR DESCRIPTION
**Pull request by mavasani**
…Microsoft.Net.RoslynDiagnostics NuGet packages

Verified it works locally:

image

### CODE REVIEW

**Comment by jinujoseph** [comment]
whats ci here ? should it say beta ?

**Comment by mavasani** [comment]
> whats ci here ? should it say beta ?

That's just the package name when CIBuild.cmd is executed locally. We will generate the correct package names on signed build machine.

**Comment by 333fred** [comment]
Could we conditionally include the Exp package only if the release version is suffixed with alpha/beta? I'm concerned about, in the future, us creating some experiment and doing a release at the same time, and shipping the release package with the experimental package.

**Comment by jinujoseph** [comment]
+1 on Freds proposal

**Comment by mavasani** [comment]
Our signed build always generates prerelease packages. We have to manually run NuGetRepack on prerelease packages to produce release packages.

**Comment by mavasani** [comment]
@333fred Are you fine with the current change?

**Comment by mavasani** [comment]
@333fred Filed https://github.com/dotnet/roslyn-tools/issues/174 to track your request.

**Pull request merged**
