### PR TITLE
Add icons and release notes for the VSIX

### PR DESCRIPTION
**Pull request by mavasani**

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @333fred @jinujoseph @heejaechang @kuhlenh

**Comment by heejaechang** [comment]
are we supposed to put binary file (icon) to git?

**Comment by heejaechang** [comment]
👍

**Comment by mavasani** [comment]
> are we supposed to put binary file (icon) to git?

Confirmed with Justin Clareburt, the PM driving this that we should put it on Github

**Comment by justcla** [comment]
Yes. The icon is part of the project.

**Comment by 333fred** [comment]
@heejaechang the issue I've always heard with binary files is the ones that _change_ often, as git can't dedup the changed parts or do intelligent diffs. Icons are fine, because they don't change often.

**Pull request merged**
