### PR TITLE
Don't report CA2257 on nested types

### LINKED ISSUE #7106: CA2257 should not be reported on nested types
### Analyzer

**Diagnostic ID**: [CA2257](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2257): `Members defined on an interface with the 'DynamicInterfaceCastableImplementationAttribute' should be 'static'`

### Analyzer source

**SDK**: [Built-in CA analyzers in .NET 8 SDK or later](https://learn.microsoft.com/dotnet/fundamentals/productivity/code-analysis)

**Version**: [SDK 8.0.100](https://dotnet.microsoft.com/download/dotnet/5.0)

### Describe the bug

The analyzer reports that nested types in a type with `[DynamicInterfaceCastableImplementation]` should be static, but the rationale for that rule does not apply to nested types.

### Steps To Reproduce

```csharp

interface Foo
{
   void Bar();
}

[DynamicInterfaceCastableImplementation]
interface FooImpl
{
     void Foo.Bar() {}

     private class C {}
}

```

### Expected behavior

No diagnostic

### Actual behavior

A diagnostic on the class declaration

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes #7106

### CODE REVIEW

**Comment by carlossanlop** [comment]
Since this is a servicing change, this would need to go through Tactics. Can you please fill out the typical template (like the one we use in runtime) and send an email to Tactics requesting approval?

**Comment by jkoritzinsky** [comment]
This is not meant to be a servicing change. Which branch do I need to target for this to be non-servicing? Is it main or a different release/8.0.yxx branch?

**Comment by carlossanlop** [comment]
It should go to main.

**Comment by carlossanlop** [comment]
I think it might be easier to resubmit the PR rather than retargeting the PR to the main branch. Otherwise a bunch of unrelated commits might end up getting included in the PR.

**Comment by jkoritzinsky** [comment]
I rebased the PR onto main and then changed the branch, so it only has my commit.

@sharwell this is ready for review

**Review by buyaa-n — APPROVED** [review]
LGTM

**Pull request merged**
