### PR TITLE
Fix issue where querying for code fixes would always hang the IDE.

### PR DESCRIPTION
**Pull request by CyrusNajmabadi**

### CODE REVIEW

**Comment by CyrusNajmabadi** [comment]
Tagging @srivatsn @mavasani 

"new Task" makes a cold task.  awaiting that cold task will always hang.  This means that any time the user tried to get a light-bulb on a line where there was one of the roslyn-analyzers, it would hang the entire IDE.

**Comment by CyrusNajmabadi** [comment]
@mavasani @srivatsn All i did was change code  I'ts not clear to me why we're getting this error:

error MSB3073: The command ""D:\j\workspace\windows_debug---c729d7ab\\Src\.nuget\Nuget.exe" restore "D:\j\workspace\windows_debug---c729d7ab\\src\Analyzers.sln"" exited with code 1.
Indication 1

**Comment by CyrusNajmabadi** [comment]
Can either of you look at thsi soon.  this is a high source of hangs.

**Comment by mavasani** [comment]
👍 Seems to me something in the repo is broken. We haven't worked on analyzers repo for a while now. I'll investigate.

**Comment by CyrusNajmabadi** [comment]
thanks.

**Comment by CyrusNajmabadi** [comment]
Also, i talked to manish about this.  But we should spin up a new version when we can to deal with the hang problem that we've been hitting over this.

**Comment by CyrusNajmabadi** [comment]
Any headway on this?

**Comment by mavasani** [comment]
Unfortunately, there are lot of other blocking high pri items on my plate right now. Will try to get to this soon...

**Comment by CyrusNajmabadi** [comment]
Note that this is a large source of hangs (presumably for analyzer authors).

**Comment by mavasani** [comment]
@dotnet-bot retest this please

**Comment by mavasani** [comment]
@CyrusNajmabadi I have checked in the fix - feel free to merge in once the tests pass.

**Comment by CyrusNajmabadi** [comment]
Thanks!

**Comment by CyrusNajmabadi** [comment]
Ok merged.  Will a new version of this automatically get pushed?  If not, who should handle that?  Thanks!

**Comment by srivatsn** [comment]
The next time there's a public release of the package (typically timed with VS releases) this will get updated.

**Pull request merged**
