### PR TITLE
Fix assert in presence of explicit cast of flow capture

### PR DESCRIPTION
**Pull request by mavasani**

### CODE REVIEW

**Comment by mavasani** [comment]
Tagging @JarLob

**Comment by JarLob** [comment]
Still asserts, although in the other place:
```cs
        private object foo(string str)
        {
            int? intVal = int.TryParse(str, out var outInt) ? outInt : (int?)null;
            return (intVal.HasValue ? (object)intVal.Value : (object)str);
        }
```

**Comment by mavasani** [comment]
Thanks @JarLob, should be fixed now.

@dotpaul can you please review? Very trivial change...

**Review by dotpaul — APPROVED** [review]
:ship:

**Comment by mavasani** [comment]
Thank you @dotpaul!

**Pull request merged**
