### PR TITLE
Update AnalyzerReleases shipped file for 7.0 release

### LINKED ISSUE #6245: TargetFramework net7.0 disables all CAxxxx rules
Just bumped my project to `.NET 7.0 RC2` (running `VS Version 17.4.0 Preview 6.0`), and realized that all code analysis rules are disabled, no matter the settings. Downgrading the project to `net6.0` re-enables all CAxxxx rules.

### Steps To Reproduce
Just create a console project with some CAxxxx violations, and target `net7.0`. No warnings are produced. Downgrade to `net6.0` to get the warnings back.

```xml
<PropertyGroup>
   <!--TargetFramework>net6.0</TargetFramework-->
   <TargetFramework>net7.0</TargetFramework>

   <OutputType>Exe</OutputType>
   <LangVersion>latest</LangVersion>
   <ImplicitUsings>enable</ImplicitUsings>
   <Nullable>enable</Nullable>
   <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
   <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
   <AnalysisMode>AllEnabledByDefault</AnalysisMode>
   <WarningLevel>9999</WarningLevel>
</PropertyGroup>
```

### Expected behavior
CAxxxx rules are checked when targeting `.NET 7`.

### Actual behavior
CAxxxx rules are checked only when targeting `.NET 6` or earlier.

### PR DESCRIPTION
**Pull request by mavasani**
Fixes #6245

I verified that locally built NuGet package with this fix resolves this issue. The NuGet package contains `analysislevel_7_XXX.editorconfig` set of editorconfig files, and setting `AnalysisLevel` to `latest-XXX` or `latest` or `7.0` passes in the appropriate editorconfig file to compiler command line

Filed #6247 to enhance the tooling to avoid regressions such as #6245 in future.

### CODE REVIEW

**Comment by mavasani** [comment]
@Evangelink @jmarolf for review

**Review by Evangelink — APPROVED** [review]

**Comment by mavasani** [comment]
@jmarolf can we do an insertion of the latest NetAnalyzers package into dotnet/sdk after this change?

**Comment by znakeeye** [comment]
Just installed `Visual Studio 17.4.0` and re-compiled my project. Still no CAxxxx warnings produced when targeting `net7.0`. Is this expected?

**Comment by mavasani** [comment]
@znakeeye The fix still needs to flow from this repo to dotnet/sdk repo and make it into the next .NET 7 servicing release. Additionally, VS also needs to move to the newer .NET 7 release with the fix for it to automatically light up. This whole code flow and release process can take some time, so I would suggest you to directly install the latest prerelease NuGet package from this feed instead: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet7/NuGet/Microsoft.CodeAnalysis.NetAnalyzers

Note that you should avoid setting `EnableNETAnalyzers` MSBuild property to true in your project file/props/targets, as that would in turn override the installed NuGet package analyzers with the old ones shipping inside the .NET SDK (which don't yet have this fix).

**Comment by znakeeye** [comment]
> @znakeeye The fix still needs to flow from this repo to dotnet/sdk repo and make it into the next .NET 7 servicing release. Additionally, VS also needs to move to the newer .NET 7 release with the fix for it to automatically light up. This whole code flow and release process can take some time, so meanwhile I would suggest you to directly install the latest prerelease NuGet package from this feed instead: https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet7/NuGet/Microsoft.CodeAnalysis.NetAnalyzers
> 
> Note that you should avoid setting `EnableNETAnalyzers` MSBuild property to true in your project file/props/targets, as that would in turn override the installed NuGet package analyzers with the old ones shipping inside the .NET SDK (which don't yet have this fix).

Ok, so in order to get it to work with `.NET 7` you should:
1. Install VS 17.4
2. Comment out `EnableNETAnalyzers`
3. Install latest prelease of [Microsoft.CodeAnalysis.NetAnalyzers](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet7/NuGet/Microsoft.CodeAnalysis.NetAnalyzers)

**Correct?** Or do we need 17.5p1? (I saw it was referenced here, somewhere...)

**Comment by jmarolf** [comment]
@mavasani I can confirm this made it into the .NET SDK here: https://github.com/dotnet/sdk/pull/28864. It should be part of the first servicing release.

**Comment by mavasani** [comment]
Thank you @jmarolf

**Comment by znakeeye** [comment]
I suppose this was fixed in `SDK 7.0.101` then?

**Comment by mavasani** [comment]
> I suppose this was fixed in `SDK 7.0.101` then?

Yes, correct.

**Pull request merged**
