### PR TITLE
Revert "Move tests to target .NET 7"

### PR DESCRIPTION
**Pull request by mavasani**
Reverts dotnet/roslyn-analyzers#6364 to fix the build break in the repo

### CODE REVIEW

**Comment by Youssef1313** [comment]
@mavasani Instead of reverting the PR, could you try targeting net8.0 instead?
I think the issue is that .NET 7 runtime isn't found starting with https://github.com/dotnet/roslyn-analyzers/pull/6409

**Comment by mavasani** [comment]
Okay, let me try on https://github.com/dotnet/roslyn-analyzers/pull/6428

**Comment by mavasani** [comment]
> I'm also curious about the move to .NET 8 SDK too early?

Do you know which PR did that? I agree we should stay on .NET 7

**Comment by mavasani** [comment]
> > I'm also curious about the move to .NET 8 SDK too early?
> 
> Do you know which PR did that? I agree we should stay on .NET 7

Seems like it happened with https://github.com/dotnet/roslyn-analyzers/pull/6409

**Comment by Youssef1313** [comment]
@mavasani Do we want to revert #6409 too?

**Comment by mavasani** [comment]
Force merging to fix the build break

**Comment by mavasani** [comment]
> @mavasani Do we want to revert #6409 too?

@jmarolf?

**Pull request merged**
