### PR TITLE
Fix for false positive unit tests

### PR DESCRIPTION
**Pull request by TKharaishvili**
Addesses the issue - https://github.com/dotnet/roslyn-analyzers/issues/2233

### CODE REVIEW

**Comment by TKharaishvili** [comment]
@mavasani I did check several times and on several test cases and can confirm that it doesn't yield false positives anymore.

However I also ran the entire suite of all unit tests in the whole solution and several of them didn't succeed. Which means this current CI build might fail too. I do think we should treat this as a separate matter though. Would you agree?

**Comment by mavasani** [comment]
@TKharaishvili Thanks. I investigated further and found that there are 20 failing code fix tests, and all of them are failing while trying to perform the default verification from the FixAll code path:

```
Result StackTrace:	
at Test.Utilities.CodeFixTestBase.VerifyDocuments(Solution solution, Document[] documents, String[] newSources) in c:\roslyn-analyzers\src\Test.Utilities\CodeFixTestBase.cs:line 173
   at Test.Utilities.CodeFixTestBase.VerifyFixAll(CodeFixRunner runner, Document[] documents, String[] newSources, FixAllScope fixAllScope, Nullable`1 codeFixIndex, Boolean allowNewCompilerDiagnostics) in c:\roslyn-analyzers\src\Test.Utilities\CodeFixTestBase.cs:line 121
   at Test.Utilities.CodeFixTestBase.VerifyFix(String language, DiagnosticAnalyzer analyzerOpt, CodeFixProvider codeFixProvider, String[] oldSources, String[] newSources, Nullable`1 codeFixIndex, Boolean allowNewCompilerDiagnostics, Boolean onlyFixFirstFixableDiagnostic, Nullable`1 testFixAllScope, Boolean allowUnsafeCode, TestValidationMode validationMode) in c:\roslyn-analyzers\src\Test.Utilities\CodeFixTestBase.cs:line 95
   at Test.Utilities.CodeFixTestBase.VerifyBasicFix(String oldSource, String newSource, Nullable`1 codeFixIndex, Boolean allowNewCompilerDiagnostics, Boolean onlyFixFirstFixableDiagnostic, Nullable`1 testFixAllScope, TestValidationMode validationMode) in c:\roslyn-analyzers\src\Test.Utilities\CodeFixTestBase.cs:line 49
   at Microsoft.CodeQuality.Analyzers.ApiDesignGuidelines.UnitTests.DefineAccessorsForAttributeArgumentsTests.VisualBasic_CA1019_AddAccessor2() in c:\roslyn-analyzers\src\Microsoft.CodeQuality.Analyzers\UnitTests\ApiDesignGuidelines\DefineAccessorsForAttributeArgumentsTests.Fixer.cs:line 303
```

These failures might either be by design (for example, the original unit test has more than one diagnostics of the same ID and hence the FixAll result is different from single code fix application result), in which case the unit tests should explicitly opt-out of default FixAll verification. These failures might also be bugs in the code fixer or the batch FixAll fixer, in which case we need to fix them. I would recommend do the following steps:

1. For all the failing 20 unit tests, explicitly opt-out of default FixAll testing by passing `testFixAllScope: null` as an explicit argument to VerifyCSharpFix or VerifyBasicFix invocations. This should ensure all tests pass. You can update this PR with these changes, and @genlu can review/sign off as appropriate.
2. File a separate tracking bug referencing this PR to investigate each of the 20 unit tests for by design versus bug. @genlu can look at these 20 affected unit tests as a follow-up investigation.

FYI: I am on vacation starting today for few weeks, so expect slow responses from me.

**Comment by TKharaishvili** [comment]
@mavasani just to clarify. Do you want me to open a separate issue for each of the 20 test cases? Or one for all of them? And is there someone else I can keep in touch with not to disturb your break?

**Comment by mavasani** [comment]
@TKharaishvili a single issue is fine - just reference this PR from that issue. You can ping @genlu on any other questions.

**Comment by TKharaishvili** [comment]
Hi @genlu the commit is up and running and here's the issue requested by @mavasani  - https://github.com/dotnet/roslyn-analyzers/issues/2237

You are the one who should merge this in if I'm not mistaken.
Thanks.

**Comment by TKharaishvili** [comment]
@mavasani Happy to help ^^

**Comment by genlu** [comment]
Thanks @TKharaishvili ! I will take a look at the FixAll test issue.

**Pull request merged**
