### PR TITLE
Ignore identity conversions in UseValueTasksCorrectly

### PR DESCRIPTION
**Pull request by stephentoub**
Fixes https://github.com/dotnet/roslyn-analyzers/issues/4271
cc: @NickCraver

### CODE REVIEW

**Review by mavasani — APPROVED** [review]

**Comment by mavasani** [comment]
@stephentoub Did you mean to target this to `release/dotnet5-rc2` branch? Master is now targeting .NET6

**Comment by stephentoub** [comment]
> Did you mean to target this to release/dotnet5-rc2 branch? Master is now targeting .NET6

In dotnet/runtime we check in first to master and then backport to a release branch when it's approved.  Does dotnet/roslyn-analyzers work differently?  If this meets whatever bar is in place for dotnet5-rc2, I'd certainly like to get it in.

**Comment by mavasani** [comment]
> In dotnet/runtime we check in first to master and then backport to a release branch when it's approved. Does dotnet/roslyn-analyzers work differently? If this meets whatever bar is in place for dotnet5-rc2, I'd certainly like to get it in.

Tagging @jmarolf @jeffhandley. We do not have any official approval process or bar as of now, but something we should put in place. For now, we merge critical bug fixes directly into dotnet5-rc2 and they flow into master through regular codeflow. I think it would be fine to retarget this PR to that branch.

**Comment by stephentoub** [comment]
Ok, thanks, retargeted.

**Pull request merged**
