### PR TITLE
Updating System.Reflection.Metadata to v1.1.0-alpha-00015 and System.Collections.Immutable to v1.1.37.0

### PR DESCRIPTION
**Pull request by tannergooding**

### CODE REVIEW

**Comment by tannergooding** [comment]
FYI. @tmeschter, @tmat, @jmarolf, @jaredpar 

This is required in order for Roslyn to update to the same. Otherwise the compiler fails to call `Assembly.GetType` for members such as `Roslyn.Diagnostics.Analyzers.Reliability.MixedVersionsOfMefAttributesAnalyzer` because it contains a method (such as `get_SupportedDiagnostics`) which returns a type (such `ImmutableArray<byte>`) that is defined in System.Collections.Immutable

**Comment by tmeschter** [comment]
No, until there is a compelling reason to consume Roslyn v1.1 the analyzers here will continue to target v1.0--and that includes the current versions of System.Reflection.Metadata and System.Collections.Immutable.

Instead, csc.exe, vbc.exe, vbcscompiler.exe, and VS need to have binding redirects from the old versions of these to the new versions. That way analyzers build against Roslyn 1.0/System.Collections.Immutable 1.1.36 continue to work properly.

**Comment by tmeschter** [comment]
:-1:

**Comment by tannergooding** [comment]
@tmeschter, seems there needed to be a binding redirect to System.Reflection.Metadata as well :)

**Pull request closed without merging**
