### PR TITLE
Update archive settings to only archive on failure

### PR DESCRIPTION
**Pull request by 333fred**
Tagging @dotnet/roslyn-analysis @tmat for review.

### CODE REVIEW

**Comment by 333fred** [comment]
@dotnet-bot test ci please

**Comment by tmat** [comment]
Looks good. Ideally we would update groovy scripts in all repos to do the same. @mmitche @tannergooding can we define some helper functions that can be used across all repos and thus minimize the amount of code in each repo script?

**Comment by tannergooding** [comment]
I thought we already had a helper function for doing this... Let me check.

**Comment by tannergooding** [comment]
The other overload looks to be deprecated. I'll let @mmitche comment here on whether adding an overload that constructs the ArchivalSettings for you is desirable.

**Comment by 333fred** [comment]
@dotnet-bot test ci please

**Comment by 333fred** [comment]
@tmat @tannergooding the reason I went from the archival method to constructing the settings by hand is because the `doNotFailIfNothingArchived` double-negative is terrible, and I had to go look at the source to figure out what it actually was.

**Comment by tmat** [comment]
Ideally i'd like to remove netci.groovy from all repos that use RepoToolset. If the script has to be in each repo can we minimize it to a single function call?

**Comment by 333fred** [comment]
@tmat and I talked a bit offline. We'd like to have a function in dotnet-ci that's just something like `useRepoToolset()` that just sets up the standard settings for a project using dotnet/roslyn-tools/repo-toolset.

**Pull request merged**
