### PR TITLE
Do not hard code certificate

### LINKED ISSUE #3012: AD0001 (NullReferenceException)
#### Analyzer package

* Microsoft.NetCore.Analyzers.Security

#### Package Version

v2.9.7 (Latest)

#### Diagnostic ID

[AD0001]

#### Repro steps

Code that breaks analyzer:

```
public static string Calculate(string unhashedNameId)
{
    if (string.IsNullOrWhiteSpace(unhashedNameId))
    {
        throw new ArgumentNullException(nameof(unhashedNameId), $"{nameof(unhashedNameId)} must not be null, empty or whitespace.");
    }

    if (!Constants.UnhashedNameIdRegex.IsMatch(unhashedNameId))
    {
        throw new ArgumentException($"{nameof(unhashedNameId)} does not match '{Constants.UnhashedNameIdRegex}'.", nameof(unhashedNameId));
    }

    using (var sha = new SHA256Managed())
    {
        byte[] textData = Encoding.UTF8.GetBytes(unhashedNameId);
        byte[] crypto = sha.ComputeHash(textData);

        var nameId = new StringBuilder();
        foreach (byte hash in crypto)
        {
            nameId.Append(hash.ToString("x2", CultureInfo.InvariantCulture));
        }

        return nameId.ToString();
    }
}
```

#### Actual behavior

Exception:

```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error	AD0001	Analyzer 'Microsoft.NetCore.Analyzers.Security.DoNotHardCodeCertificate' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.	*** (netstandard2.0)		1	Active	Analyzer 'Microsoft.NetCore.Analyzers.Security.DoNotHardCodeCertificate' threw the following exception:
'Exception occurred with following context:
Compilation: ***
IOperation: Invocation
SyntaxTree: ***\NameIdentifier.cs
SyntaxNode: Encoding.UTF8.GetBytes(unhashedNameId ... [InvocationExpressionSyntax]@[1011..1049) (27,34)-(27,72)

System.NullReferenceException: Object reference not set to an instance of an object.
   at Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.TaintedDataSymbolMapExtensions.<>c__DisplayClass0_0.<IsSourceMethod>b__5(IArgumentOperation o)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.TaintedDataSymbolMapExtensions.<>c__DisplayClass0_0.<IsSourceMethod>b__3(ValueTuple`2 s)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.TaintedDataSymbolMapExtensions.IsSourceMethod(TaintedDataSymbolMap`1 sourceSymbolMap, IMethodSymbol method, ImmutableArray`1 arguments, Lazy`1 pointsToAnalysisResult, Lazy`1 valueContentAnalysisResult, PooledHashSet`1& allTaintedTargets)
   at Microsoft.NetCore.Analyzers.Security.SourceTriggeredTaintedDataAnalyzerBase.<>c__DisplayClass6_1.<Initialize>b__3(OperationAnalysisContext operationAnalysisContext)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__54_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----
'.
```

### PR DESCRIPTION
**Pull request by LLLXXXCCC**
#3012

1. I think this issue might be caused by null valueContentAnalysisResult.

2. Fix the wrong use of Lazy<>.

### CODE REVIEW

**Comment by dotpaul** [comment]
Any unit tests for this bug? #3012 had example code.

Also, with ability to disable dataflow analysis via .editorconfig, we can't assume that we'll get back non-null PointsToAnalysisResults or ValueContentAnalysisResults.

**Comment by mavasani** [comment]
> Also, with ability to disable dataflow analysis via .editorconfig, we can't assume that we'll get back non-null PointsToAnalysisResults or ValueContentAnalysisResults.

Agreed. I am also going to work on enabling C# 8.0 nullable reference types in the repo to avoid more such NREs.

**Comment by LLLXXXCCC** [comment]
> Any unit tests for this bug? #3012 had example code.
> 
> Also, with ability to disable dataflow analysis via .editorconfig, we can't assume that we'll get back non-null PointsToAnalysisResults or ValueContentAnalysisResults.

That example code doesn't have any problem. The problem, I think, is caused by concurrency executing. For example, when two threads executing IsSourceMethod(). Thread A sets valueContentComputed as true, but doesn't reach returning valueContentResult yet. Thread B will get that valueContentComputed is true, than B returns a null valueContentResult. Then 'valueContentAnalysisResult.Value[o.Kind, o.Syntax]' will throw that NRE exception.

**Comment by dotpaul** [comment]
Can you come up with a unit test that reproduces the NullReferenceException, even if it's not consistently? Or example code compiled outside of a unit test that reproduces the NullReferenceException?

**Comment by LLLXXXCCC** [comment]
> Can you come up with a unit test that reproduces the NullReferenceException, even if it's not consistently? Or example code compiled outside of a unit test that reproduces the NullReferenceException?

Sorry. I was wrong, concurrency is fine.  I return null instead of pointsToResult in the initialization of Lazy<PointsToAnalysisResult> then got a exception which is quite similar with the one mentioned in the issue:

`at Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.TaintedDataSymbolMapExtensions.<>c__DisplayClass0_0.<IsSourceMethod>b__5(IArgumentOperation o) in D:\Code\LLLXXXCCC\roslyn-analyzers\src\Utilities\FlowAnalysis\FlowAnalysis\Analysis\TaintedDataAnalysis\TaintedDataSymbolMapExtensions.cs:line 82
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at System.Collections.Immutable.ImmutableArray.ToImmutableArray[TSource](IEnumerable`1 items)
   at Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.TaintedDataSymbolMapExtensions.<>c__DisplayClass0_0.<IsSourceMethod>b__3(ValueTuple`2 s) in D:\Code\LLLXXXCCC\roslyn-analyzers\src\Utilities\FlowAnalysis\FlowAnalysis\Analysis\TaintedDataAnalysis\TaintedDataSymbolMapExtensions.cs:line 81
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at Analyzer.Utilities.FlowAnalysis.Analysis.TaintedDataAnalysis.TaintedDataSymbolMapExtensions.IsSourceMethod(TaintedDataSymbolMap`1 sourceSymbolMap, IMethodSymbol method, ImmutableArray`1 arguments, Lazy`1 pointsToAnalysisResult, Lazy`1 valueContentAnalysisResult, PooledHashSet`1& allTaintedTargets) in D:\Code\LLLXXXCCC\roslyn-analyzers\src\Utilities\FlowAnalysis\FlowAnalysis\Analysis\TaintedDataAnalysis\TaintedDataSymbolMapExtensions.cs:line 91
`

I can't figure out what code error will cause a null pointsToResult unless it is null computed by TryGetOrComputeResult().

**Comment by LLLXXXCCC** [comment]
By the way, the old way didn't take the advantage of Lazy<T>. It always compute the Lazy.Value every time so we need pointsToComputed flag. Now, I correct it and Lazy.Value will be computed only once.

**Comment by dotpaul** [comment]
Changing how Lazy is used is fine (maybe there is some concurrency thing going on, and the code didn't look thread safe), but please add a unit test for the reported code, even if it doesn't repro.

**Comment by dotpaul** [comment]
:ship:

**Pull request merged**
