### PR TITLE
Embed PerformanceSensitiveAttribute in projects that reference the analyzers

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by jaredpar** [comment]
@tmat should look at the targets file.

**Comment by sharwell** [comment]
@tmat please let us know if there is anything here you'd like us to change 😄

**Comment by tmat** [comment]
If I understand the change well, the project referencing the analyzer package will include the file contained in the package?

If that is so, this will break Source Link validation because the file is not in the source directory. 
To fix it we should embed the source in the PDB.

**Comment by sharwell** [comment]
@tmat thank you I filed a big for that!

**Pull request merged**
