### PR TITLE
Remove PInvokeDeclarationsShouldBePortable analyzer...

### LINKED ISSUE #587: Port FxCop rule CA1901: PInvokeDeclarationsShouldBePortable
**Title:** PInvoke declarations should be portable

**Description:**

This rule evaluates the size of each parameter and the return value of a P/Invoke, and verifies that the size of the parameter is correct when marshaled to unmanaged code on 32-bit and 64-bit operating systems.

**Dependency:** See CA2101

**Notes:**

### PR DESCRIPTION
**Pull request by KevinH-MS**
It's been decided that the usefulness of this analyzer is outweighed by the requirement of maintaining a binary baseline of all known Win32 APIs ("Repository\system32.bin").

Fixes #587

### CODE REVIEW

**Comment by KevinH-MS** [comment]
FYI @srivatsn @lgolding @nguerrera

**Comment by lgolding** [comment]
Closing per discussion between @KevinH-MS, @srivatsn, and @nguerrera.

**Comment by KevinH-MS** [comment]
This is the PR to remove the analyzer.

**Comment by lgolding** [comment]
Oops. OK, LGTM.

**Comment by srivatsn** [comment]
:+1:

**Pull request merged**
