### PR TITLE
LOC CHECKIN | dotnet/roslyn-analyzers master | 20200512

### PR DESCRIPTION
**Pull request by v-chmart**
Localization update

### CODE REVIEW

**Comment by mavasani** [comment]
@v-chmart There are build failures.

**Comment by v-chmart** [comment]
> @v-chmart There are build failures.

The build comes up with this message: 
'xlf\MicrosoftCodeQualityAnalyzersResources.cs.xlf' is out-of-date with 'MicrosoftCodeQualityAnalyzersResources.resx'

Could you check if xlf files have been updated? I only made change on those.

**Comment by mavasani** [comment]
@v-chmart Would you be able to pull the latest changes from master and resolve merge conflicts? Additionally, please run `build.cmd` in repo root to build all solutions in the repo and update their xlf files.

**Comment by janbaltus** [comment]
@mavasani localization team deliver xlf files only. We should not run any other processes and tools

**Comment by mavasani** [comment]
@v-chmart @janbaltus Sorry, let me be more explicit. This PR seems to be based off resx files which are not up-to-date with master. This seems to be causing the build to fail as xlf file changes are touching resource strings which have either been deleted OR not touching newly added resource strings.

**Comment by v-chmart** [comment]
@mavasani Let me create a new PR with updated files. If the builds succeed I will close this PR.

**Pull request closed without merging**
